/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.resume.ui.internal.ResumeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ResumeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ResumeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ResumeActivator activator = ResumeActivator.getInstance();
		return activator != null ? activator.getInjector(ResumeActivator.ORG_XTEXT_EXAMPLE_RESUME_RESUME) : null;
	}

}
