/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.resume.ui.internal.ResumeActivator;

public class ResumeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ResumeActivator.getInstance().getInjector("org.xtext.example.resume.Resume");
	}

}
