/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.resume.resume.AllFilter;
import org.xtext.example.resume.resume.ResumePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>All Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AllFilterImpl extends FilterImpl implements AllFilter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllFilterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResumePackage.Literals.ALL_FILTER;
  }

} //AllFilterImpl
