/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.resume.resume.Degree;
import org.xtext.example.resume.resume.ResumePackage;
import org.xtext.example.resume.resume.StringList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Degree</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.impl.DegreeImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.DegreeImpl#getInstitution <em>Institution</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.DegreeImpl#getGraduationDate <em>Graduation Date</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.DegreeImpl#getCountry <em>Country</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.DegreeImpl#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DegreeImpl extends MinimalEObjectImpl.Container implements Degree
{
  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getInstitution() <em>Institution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstitution()
   * @generated
   * @ordered
   */
  protected static final String INSTITUTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInstitution() <em>Institution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstitution()
   * @generated
   * @ordered
   */
  protected String institution = INSTITUTION_EDEFAULT;

  /**
   * The default value of the '{@link #getGraduationDate() <em>Graduation Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGraduationDate()
   * @generated
   * @ordered
   */
  protected static final String GRADUATION_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGraduationDate() <em>Graduation Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGraduationDate()
   * @generated
   * @ordered
   */
  protected String graduationDate = GRADUATION_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getCountry() <em>Country</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCountry()
   * @generated
   * @ordered
   */
  protected static final String COUNTRY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCountry() <em>Country</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCountry()
   * @generated
   * @ordered
   */
  protected String country = COUNTRY_EDEFAULT;

  /**
   * The cached value of the '{@link #getTags() <em>Tags</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTags()
   * @generated
   * @ordered
   */
  protected StringList tags;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DegreeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResumePackage.Literals.DEGREE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.DEGREE__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInstitution()
  {
    return institution;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInstitution(String newInstitution)
  {
    String oldInstitution = institution;
    institution = newInstitution;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.DEGREE__INSTITUTION, oldInstitution, institution));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getGraduationDate()
  {
    return graduationDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGraduationDate(String newGraduationDate)
  {
    String oldGraduationDate = graduationDate;
    graduationDate = newGraduationDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.DEGREE__GRADUATION_DATE, oldGraduationDate, graduationDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCountry()
  {
    return country;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCountry(String newCountry)
  {
    String oldCountry = country;
    country = newCountry;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.DEGREE__COUNTRY, oldCountry, country));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringList getTags()
  {
    return tags;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTags(StringList newTags, NotificationChain msgs)
  {
    StringList oldTags = tags;
    tags = newTags;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResumePackage.DEGREE__TAGS, oldTags, newTags);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTags(StringList newTags)
  {
    if (newTags != tags)
    {
      NotificationChain msgs = null;
      if (tags != null)
        msgs = ((InternalEObject)tags).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResumePackage.DEGREE__TAGS, null, msgs);
      if (newTags != null)
        msgs = ((InternalEObject)newTags).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResumePackage.DEGREE__TAGS, null, msgs);
      msgs = basicSetTags(newTags, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.DEGREE__TAGS, newTags, newTags));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ResumePackage.DEGREE__TAGS:
        return basicSetTags(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ResumePackage.DEGREE__TITLE:
        return getTitle();
      case ResumePackage.DEGREE__INSTITUTION:
        return getInstitution();
      case ResumePackage.DEGREE__GRADUATION_DATE:
        return getGraduationDate();
      case ResumePackage.DEGREE__COUNTRY:
        return getCountry();
      case ResumePackage.DEGREE__TAGS:
        return getTags();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ResumePackage.DEGREE__TITLE:
        setTitle((String)newValue);
        return;
      case ResumePackage.DEGREE__INSTITUTION:
        setInstitution((String)newValue);
        return;
      case ResumePackage.DEGREE__GRADUATION_DATE:
        setGraduationDate((String)newValue);
        return;
      case ResumePackage.DEGREE__COUNTRY:
        setCountry((String)newValue);
        return;
      case ResumePackage.DEGREE__TAGS:
        setTags((StringList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.DEGREE__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case ResumePackage.DEGREE__INSTITUTION:
        setInstitution(INSTITUTION_EDEFAULT);
        return;
      case ResumePackage.DEGREE__GRADUATION_DATE:
        setGraduationDate(GRADUATION_DATE_EDEFAULT);
        return;
      case ResumePackage.DEGREE__COUNTRY:
        setCountry(COUNTRY_EDEFAULT);
        return;
      case ResumePackage.DEGREE__TAGS:
        setTags((StringList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.DEGREE__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case ResumePackage.DEGREE__INSTITUTION:
        return INSTITUTION_EDEFAULT == null ? institution != null : !INSTITUTION_EDEFAULT.equals(institution);
      case ResumePackage.DEGREE__GRADUATION_DATE:
        return GRADUATION_DATE_EDEFAULT == null ? graduationDate != null : !GRADUATION_DATE_EDEFAULT.equals(graduationDate);
      case ResumePackage.DEGREE__COUNTRY:
        return COUNTRY_EDEFAULT == null ? country != null : !COUNTRY_EDEFAULT.equals(country);
      case ResumePackage.DEGREE__TAGS:
        return tags != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (title: ");
    result.append(title);
    result.append(", institution: ");
    result.append(institution);
    result.append(", graduationDate: ");
    result.append(graduationDate);
    result.append(", country: ");
    result.append(country);
    result.append(')');
    return result.toString();
  }

} //DegreeImpl
