/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.resume.resume.Customization;
import org.xtext.example.resume.resume.Metadata;
import org.xtext.example.resume.resume.Profile;
import org.xtext.example.resume.resume.ResumePackage;
import org.xtext.example.resume.resume.Section;
import org.xtext.example.resume.resume.Userdata;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Profile</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.impl.ProfileImpl#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.ProfileImpl#getUserdata <em>Userdata</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.ProfileImpl#getSections <em>Sections</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.ProfileImpl#getCustomization <em>Customization</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProfileImpl extends MinimalEObjectImpl.Container implements Profile
{
  /**
   * The cached value of the '{@link #getMetadata() <em>Metadata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetadata()
   * @generated
   * @ordered
   */
  protected Metadata metadata;

  /**
   * The cached value of the '{@link #getUserdata() <em>Userdata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUserdata()
   * @generated
   * @ordered
   */
  protected Userdata userdata;

  /**
   * The cached value of the '{@link #getSections() <em>Sections</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSections()
   * @generated
   * @ordered
   */
  protected EList<Section> sections;

  /**
   * The cached value of the '{@link #getCustomization() <em>Customization</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomization()
   * @generated
   * @ordered
   */
  protected Customization customization;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProfileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResumePackage.Literals.PROFILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Metadata getMetadata()
  {
    return metadata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMetadata(Metadata newMetadata, NotificationChain msgs)
  {
    Metadata oldMetadata = metadata;
    metadata = newMetadata;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResumePackage.PROFILE__METADATA, oldMetadata, newMetadata);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMetadata(Metadata newMetadata)
  {
    if (newMetadata != metadata)
    {
      NotificationChain msgs = null;
      if (metadata != null)
        msgs = ((InternalEObject)metadata).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResumePackage.PROFILE__METADATA, null, msgs);
      if (newMetadata != null)
        msgs = ((InternalEObject)newMetadata).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResumePackage.PROFILE__METADATA, null, msgs);
      msgs = basicSetMetadata(newMetadata, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.PROFILE__METADATA, newMetadata, newMetadata));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Userdata getUserdata()
  {
    return userdata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUserdata(Userdata newUserdata, NotificationChain msgs)
  {
    Userdata oldUserdata = userdata;
    userdata = newUserdata;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResumePackage.PROFILE__USERDATA, oldUserdata, newUserdata);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUserdata(Userdata newUserdata)
  {
    if (newUserdata != userdata)
    {
      NotificationChain msgs = null;
      if (userdata != null)
        msgs = ((InternalEObject)userdata).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResumePackage.PROFILE__USERDATA, null, msgs);
      if (newUserdata != null)
        msgs = ((InternalEObject)newUserdata).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResumePackage.PROFILE__USERDATA, null, msgs);
      msgs = basicSetUserdata(newUserdata, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.PROFILE__USERDATA, newUserdata, newUserdata));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Section> getSections()
  {
    if (sections == null)
    {
      sections = new EObjectContainmentEList<Section>(Section.class, this, ResumePackage.PROFILE__SECTIONS);
    }
    return sections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Customization getCustomization()
  {
    return customization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCustomization(Customization newCustomization, NotificationChain msgs)
  {
    Customization oldCustomization = customization;
    customization = newCustomization;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResumePackage.PROFILE__CUSTOMIZATION, oldCustomization, newCustomization);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCustomization(Customization newCustomization)
  {
    if (newCustomization != customization)
    {
      NotificationChain msgs = null;
      if (customization != null)
        msgs = ((InternalEObject)customization).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResumePackage.PROFILE__CUSTOMIZATION, null, msgs);
      if (newCustomization != null)
        msgs = ((InternalEObject)newCustomization).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResumePackage.PROFILE__CUSTOMIZATION, null, msgs);
      msgs = basicSetCustomization(newCustomization, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.PROFILE__CUSTOMIZATION, newCustomization, newCustomization));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ResumePackage.PROFILE__METADATA:
        return basicSetMetadata(null, msgs);
      case ResumePackage.PROFILE__USERDATA:
        return basicSetUserdata(null, msgs);
      case ResumePackage.PROFILE__SECTIONS:
        return ((InternalEList<?>)getSections()).basicRemove(otherEnd, msgs);
      case ResumePackage.PROFILE__CUSTOMIZATION:
        return basicSetCustomization(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ResumePackage.PROFILE__METADATA:
        return getMetadata();
      case ResumePackage.PROFILE__USERDATA:
        return getUserdata();
      case ResumePackage.PROFILE__SECTIONS:
        return getSections();
      case ResumePackage.PROFILE__CUSTOMIZATION:
        return getCustomization();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ResumePackage.PROFILE__METADATA:
        setMetadata((Metadata)newValue);
        return;
      case ResumePackage.PROFILE__USERDATA:
        setUserdata((Userdata)newValue);
        return;
      case ResumePackage.PROFILE__SECTIONS:
        getSections().clear();
        getSections().addAll((Collection<? extends Section>)newValue);
        return;
      case ResumePackage.PROFILE__CUSTOMIZATION:
        setCustomization((Customization)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.PROFILE__METADATA:
        setMetadata((Metadata)null);
        return;
      case ResumePackage.PROFILE__USERDATA:
        setUserdata((Userdata)null);
        return;
      case ResumePackage.PROFILE__SECTIONS:
        getSections().clear();
        return;
      case ResumePackage.PROFILE__CUSTOMIZATION:
        setCustomization((Customization)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.PROFILE__METADATA:
        return metadata != null;
      case ResumePackage.PROFILE__USERDATA:
        return userdata != null;
      case ResumePackage.PROFILE__SECTIONS:
        return sections != null && !sections.isEmpty();
      case ResumePackage.PROFILE__CUSTOMIZATION:
        return customization != null;
    }
    return super.eIsSet(featureID);
  }

} //ProfileImpl
