/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.resume.resume.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ResumeFactoryImpl extends EFactoryImpl implements ResumeFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ResumeFactory init()
  {
    try
    {
      ResumeFactory theResumeFactory = (ResumeFactory)EPackage.Registry.INSTANCE.getEFactory(ResumePackage.eNS_URI);
      if (theResumeFactory != null)
      {
        return theResumeFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ResumeFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResumeFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ResumePackage.PROFILE: return createProfile();
      case ResumePackage.METADATA: return createMetadata();
      case ResumePackage.USERDATA: return createUserdata();
      case ResumePackage.SECTION: return createSection();
      case ResumePackage.EXPERIENCE: return createExperience();
      case ResumePackage.JOB: return createJob();
      case ResumePackage.PROJECTS: return createProjects();
      case ResumePackage.PROJECT: return createProject();
      case ResumePackage.EDUCATION: return createEducation();
      case ResumePackage.DEGREE: return createDegree();
      case ResumePackage.SKILLS: return createSkills();
      case ResumePackage.SKILL: return createSkill();
      case ResumePackage.INTERESTS: return createInterests();
      case ResumePackage.LANGUAGES: return createLanguages();
      case ResumePackage.METRICS: return createMetrics();
      case ResumePackage.METRIC: return createMetric();
      case ResumePackage.EXPRESSION: return createExpression();
      case ResumePackage.CUSTOMIZATION: return createCustomization();
      case ResumePackage.RULE: return createRule();
      case ResumePackage.FILTER: return createFilter();
      case ResumePackage.GENERAL_FILTER: return createGeneralFilter();
      case ResumePackage.TEMPORAL_FILTER: return createTemporalFilter();
      case ResumePackage.ALL_FILTER: return createAllFilter();
      case ResumePackage.STRING_LIST: return createStringList();
      case ResumePackage.SUBTRACTION: return createSubtraction();
      case ResumePackage.NUMBER_LITERAL: return createNumberLiteral();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ResumePackage.SECTION_TYPE:
        return createSectionTypeFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ResumePackage.SECTION_TYPE:
        return convertSectionTypeToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Profile createProfile()
  {
    ProfileImpl profile = new ProfileImpl();
    return profile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Metadata createMetadata()
  {
    MetadataImpl metadata = new MetadataImpl();
    return metadata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Userdata createUserdata()
  {
    UserdataImpl userdata = new UserdataImpl();
    return userdata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Section createSection()
  {
    SectionImpl section = new SectionImpl();
    return section;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Experience createExperience()
  {
    ExperienceImpl experience = new ExperienceImpl();
    return experience;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Job createJob()
  {
    JobImpl job = new JobImpl();
    return job;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Projects createProjects()
  {
    ProjectsImpl projects = new ProjectsImpl();
    return projects;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Project createProject()
  {
    ProjectImpl project = new ProjectImpl();
    return project;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Education createEducation()
  {
    EducationImpl education = new EducationImpl();
    return education;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Degree createDegree()
  {
    DegreeImpl degree = new DegreeImpl();
    return degree;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Skills createSkills()
  {
    SkillsImpl skills = new SkillsImpl();
    return skills;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Skill createSkill()
  {
    SkillImpl skill = new SkillImpl();
    return skill;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interests createInterests()
  {
    InterestsImpl interests = new InterestsImpl();
    return interests;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Languages createLanguages()
  {
    LanguagesImpl languages = new LanguagesImpl();
    return languages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Metrics createMetrics()
  {
    MetricsImpl metrics = new MetricsImpl();
    return metrics;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Metric createMetric()
  {
    MetricImpl metric = new MetricImpl();
    return metric;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Customization createCustomization()
  {
    CustomizationImpl customization = new CustomizationImpl();
    return customization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rule createRule()
  {
    RuleImpl rule = new RuleImpl();
    return rule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Filter createFilter()
  {
    FilterImpl filter = new FilterImpl();
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralFilter createGeneralFilter()
  {
    GeneralFilterImpl generalFilter = new GeneralFilterImpl();
    return generalFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TemporalFilter createTemporalFilter()
  {
    TemporalFilterImpl temporalFilter = new TemporalFilterImpl();
    return temporalFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AllFilter createAllFilter()
  {
    AllFilterImpl allFilter = new AllFilterImpl();
    return allFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringList createStringList()
  {
    StringListImpl stringList = new StringListImpl();
    return stringList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Subtraction createSubtraction()
  {
    SubtractionImpl subtraction = new SubtractionImpl();
    return subtraction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumberLiteral createNumberLiteral()
  {
    NumberLiteralImpl numberLiteral = new NumberLiteralImpl();
    return numberLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SectionType createSectionTypeFromString(EDataType eDataType, String initialValue)
  {
    SectionType result = SectionType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertSectionTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ResumePackage getResumePackage()
  {
    return (ResumePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ResumePackage getPackage()
  {
    return ResumePackage.eINSTANCE;
  }

} //ResumeFactoryImpl
