/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.resume.resume.ResumePackage;
import org.xtext.example.resume.resume.Skill;
import org.xtext.example.resume.resume.Skills;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Skills</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.impl.SkillsImpl#getSkills <em>Skills</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SkillsImpl extends SectionImpl implements Skills
{
  /**
   * The cached value of the '{@link #getSkills() <em>Skills</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSkills()
   * @generated
   * @ordered
   */
  protected EList<Skill> skills;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SkillsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResumePackage.Literals.SKILLS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Skill> getSkills()
  {
    if (skills == null)
    {
      skills = new EObjectContainmentEList<Skill>(Skill.class, this, ResumePackage.SKILLS__SKILLS);
    }
    return skills;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ResumePackage.SKILLS__SKILLS:
        return ((InternalEList<?>)getSkills()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ResumePackage.SKILLS__SKILLS:
        return getSkills();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ResumePackage.SKILLS__SKILLS:
        getSkills().clear();
        getSkills().addAll((Collection<? extends Skill>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.SKILLS__SKILLS:
        getSkills().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.SKILLS__SKILLS:
        return skills != null && !skills.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SkillsImpl
