/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ResumeStandaloneSetup extends ResumeStandaloneSetupGenerated {

	public static void doSetup() {
		new ResumeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
