/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.resume.ResumeRuntimeModule;
import org.xtext.example.resume.ResumeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ResumeIdeSetup extends ResumeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ResumeRuntimeModule(), new ResumeIdeModule()));
	}
	
}
