/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getAllFilter()
 * @model
 * @generated
 */
public interface AllFilter extends Filter
{
} // AllFilter
