/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customization</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Customization#getLanguage <em>Language</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Customization#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getCustomization()
 * @model
 * @generated
 */
public interface Customization extends EObject
{
  /**
   * Returns the value of the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Language</em>' attribute.
   * @see #setLanguage(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getCustomization_Language()
   * @model
   * @generated
   */
  String getLanguage();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Customization#getLanguage <em>Language</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Language</em>' attribute.
   * @see #getLanguage()
   * @generated
   */
  void setLanguage(String value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.resume.resume.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.xtext.example.resume.resume.ResumePackage#getCustomization_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Customization
