/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Degree</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Degree#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Degree#getInstitution <em>Institution</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Degree#getGraduationDate <em>Graduation Date</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Degree#getCountry <em>Country</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Degree#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getDegree()
 * @model
 * @generated
 */
public interface Degree extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getDegree_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Degree#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Institution</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Institution</em>' attribute.
   * @see #setInstitution(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getDegree_Institution()
   * @model
   * @generated
   */
  String getInstitution();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Degree#getInstitution <em>Institution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Institution</em>' attribute.
   * @see #getInstitution()
   * @generated
   */
  void setInstitution(String value);

  /**
   * Returns the value of the '<em><b>Graduation Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Graduation Date</em>' attribute.
   * @see #setGraduationDate(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getDegree_GraduationDate()
   * @model
   * @generated
   */
  String getGraduationDate();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Degree#getGraduationDate <em>Graduation Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Graduation Date</em>' attribute.
   * @see #getGraduationDate()
   * @generated
   */
  void setGraduationDate(String value);

  /**
   * Returns the value of the '<em><b>Country</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Country</em>' attribute.
   * @see #setCountry(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getDegree_Country()
   * @model
   * @generated
   */
  String getCountry();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Degree#getCountry <em>Country</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Country</em>' attribute.
   * @see #getCountry()
   * @generated
   */
  void setCountry(String value);

  /**
   * Returns the value of the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' containment reference.
   * @see #setTags(StringList)
   * @see org.xtext.example.resume.resume.ResumePackage#getDegree_Tags()
   * @model containment="true"
   * @generated
   */
  StringList getTags();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Degree#getTags <em>Tags</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tags</em>' containment reference.
   * @see #getTags()
   * @generated
   */
  void setTags(StringList value);

} // Degree
