/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Experience</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Experience#getJobs <em>Jobs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getExperience()
 * @model
 * @generated
 */
public interface Experience extends Section
{
  /**
   * Returns the value of the '<em><b>Jobs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.resume.resume.Job}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jobs</em>' containment reference list.
   * @see org.xtext.example.resume.resume.ResumePackage#getExperience_Jobs()
   * @model containment="true"
   * @generated
   */
  EList<Job> getJobs();

} // Experience
