/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getFilter()
 * @model
 * @generated
 */
public interface Filter extends EObject
{
} // Filter
