/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.GeneralFilter#getTag <em>Tag</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getGeneralFilter()
 * @model
 * @generated
 */
public interface GeneralFilter extends Filter
{
  /**
   * Returns the value of the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tag</em>' attribute.
   * @see #setTag(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getGeneralFilter_Tag()
   * @model
   * @generated
   */
  String getTag();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.GeneralFilter#getTag <em>Tag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tag</em>' attribute.
   * @see #getTag()
   * @generated
   */
  void setTag(String value);

} // GeneralFilter
