/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interests</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Interests#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getInterests()
 * @model
 * @generated
 */
public interface Interests extends Section
{
  /**
   * Returns the value of the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' containment reference.
   * @see #setTags(StringList)
   * @see org.xtext.example.resume.resume.ResumePackage#getInterests_Tags()
   * @model containment="true"
   * @generated
   */
  StringList getTags();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Interests#getTags <em>Tags</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tags</em>' containment reference.
   * @see #getTags()
   * @generated
   */
  void setTags(StringList value);

} // Interests
