/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Job</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Job#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Job#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Job#getCompany <em>Company</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Job#getStartDate <em>Start Date</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Job#getEndDate <em>End Date</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Job#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getJob()
 * @model
 * @generated
 */
public interface Job extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getJob_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Job#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(StringList)
   * @see org.xtext.example.resume.resume.ResumePackage#getJob_Description()
   * @model containment="true"
   * @generated
   */
  StringList getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Job#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(StringList value);

  /**
   * Returns the value of the '<em><b>Company</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Company</em>' attribute.
   * @see #setCompany(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getJob_Company()
   * @model
   * @generated
   */
  String getCompany();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Job#getCompany <em>Company</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Company</em>' attribute.
   * @see #getCompany()
   * @generated
   */
  void setCompany(String value);

  /**
   * Returns the value of the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Date</em>' attribute.
   * @see #setStartDate(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getJob_StartDate()
   * @model
   * @generated
   */
  String getStartDate();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Job#getStartDate <em>Start Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Date</em>' attribute.
   * @see #getStartDate()
   * @generated
   */
  void setStartDate(String value);

  /**
   * Returns the value of the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Date</em>' attribute.
   * @see #setEndDate(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getJob_EndDate()
   * @model
   * @generated
   */
  String getEndDate();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Job#getEndDate <em>End Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Date</em>' attribute.
   * @see #getEndDate()
   * @generated
   */
  void setEndDate(String value);

  /**
   * Returns the value of the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' containment reference.
   * @see #setTags(StringList)
   * @see org.xtext.example.resume.resume.ResumePackage#getJob_Tags()
   * @model containment="true"
   * @generated
   */
  StringList getTags();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Job#getTags <em>Tags</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tags</em>' containment reference.
   * @see #getTags()
   * @generated
   */
  void setTags(StringList value);

} // Job
