/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metrics</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Metrics#getMetrics <em>Metrics</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getMetrics()
 * @model
 * @generated
 */
public interface Metrics extends Section
{
  /**
   * Returns the value of the '<em><b>Metrics</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.resume.resume.Metric}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metrics</em>' containment reference list.
   * @see org.xtext.example.resume.resume.ResumePackage#getMetrics_Metrics()
   * @model containment="true"
   * @generated
   */
  EList<Metric> getMetrics();

} // Metrics
