/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Project#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Project#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Project#getTechnologies <em>Technologies</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Project#getLink <em>Link</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Project#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getProject()
 * @model
 * @generated
 */
public interface Project extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getProject_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Project#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(StringList)
   * @see org.xtext.example.resume.resume.ResumePackage#getProject_Description()
   * @model containment="true"
   * @generated
   */
  StringList getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Project#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(StringList value);

  /**
   * Returns the value of the '<em><b>Technologies</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Technologies</em>' containment reference.
   * @see #setTechnologies(StringList)
   * @see org.xtext.example.resume.resume.ResumePackage#getProject_Technologies()
   * @model containment="true"
   * @generated
   */
  StringList getTechnologies();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Project#getTechnologies <em>Technologies</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Technologies</em>' containment reference.
   * @see #getTechnologies()
   * @generated
   */
  void setTechnologies(StringList value);

  /**
   * Returns the value of the '<em><b>Link</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link</em>' attribute.
   * @see #setLink(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getProject_Link()
   * @model
   * @generated
   */
  String getLink();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Project#getLink <em>Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link</em>' attribute.
   * @see #getLink()
   * @generated
   */
  void setLink(String value);

  /**
   * Returns the value of the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' containment reference.
   * @see #setTags(StringList)
   * @see org.xtext.example.resume.resume.ResumePackage#getProject_Tags()
   * @model containment="true"
   * @generated
   */
  StringList getTags();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Project#getTags <em>Tags</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tags</em>' containment reference.
   * @see #getTags()
   * @generated
   */
  void setTags(StringList value);

} // Project
