/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Projects</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Projects#getProjects <em>Projects</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getProjects()
 * @model
 * @generated
 */
public interface Projects extends Section
{
  /**
   * Returns the value of the '<em><b>Projects</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.resume.resume.Project}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projects</em>' containment reference list.
   * @see org.xtext.example.resume.resume.ResumePackage#getProjects_Projects()
   * @model containment="true"
   * @generated
   */
  EList<Project> getProjects();

} // Projects
