/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.resume.resume.ResumeFactory
 * @model kind="package"
 * @generated
 */
public interface ResumePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "resume";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/resume/Resume";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "resume";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ResumePackage eINSTANCE = org.xtext.example.resume.resume.impl.ResumePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.ProfileImpl <em>Profile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.ProfileImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getProfile()
   * @generated
   */
  int PROFILE = 0;

  /**
   * The feature id for the '<em><b>Metadata</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROFILE__METADATA = 0;

  /**
   * The feature id for the '<em><b>Userdata</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROFILE__USERDATA = 1;

  /**
   * The feature id for the '<em><b>Sections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROFILE__SECTIONS = 2;

  /**
   * The feature id for the '<em><b>Customization</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROFILE__CUSTOMIZATION = 3;

  /**
   * The number of structural features of the '<em>Profile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROFILE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.MetadataImpl <em>Metadata</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.MetadataImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getMetadata()
   * @generated
   */
  int METADATA = 1;

  /**
   * The feature id for the '<em><b>Style</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__STYLE = 0;

  /**
   * The feature id for the '<em><b>Font</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__FONT = 1;

  /**
   * The feature id for the '<em><b>Img Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__IMG_PATH = 2;

  /**
   * The number of structural features of the '<em>Metadata</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.UserdataImpl <em>Userdata</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.UserdataImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getUserdata()
   * @generated
   */
  int USERDATA = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USERDATA__NAME = 0;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USERDATA__EMAIL = 1;

  /**
   * The feature id for the '<em><b>Telephone Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USERDATA__TELEPHONE_NUMBER = 2;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USERDATA__DIRECTION = 3;

  /**
   * The feature id for the '<em><b>City</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USERDATA__CITY = 4;

  /**
   * The feature id for the '<em><b>Country</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USERDATA__COUNTRY = 5;

  /**
   * The number of structural features of the '<em>Userdata</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USERDATA_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.SectionImpl <em>Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.SectionImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSection()
   * @generated
   */
  int SECTION = 3;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__LANGUAGE = 0;

  /**
   * The number of structural features of the '<em>Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.ExperienceImpl <em>Experience</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.ExperienceImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getExperience()
   * @generated
   */
  int EXPERIENCE = 4;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE__LANGUAGE = SECTION__LANGUAGE;

  /**
   * The feature id for the '<em><b>Jobs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE__JOBS = SECTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Experience</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE_FEATURE_COUNT = SECTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.JobImpl <em>Job</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.JobImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getJob()
   * @generated
   */
  int JOB = 5;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Company</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__COMPANY = 2;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__START_DATE = 3;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__END_DATE = 4;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__TAGS = 5;

  /**
   * The number of structural features of the '<em>Job</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.ProjectsImpl <em>Projects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.ProjectsImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getProjects()
   * @generated
   */
  int PROJECTS = 6;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTS__LANGUAGE = SECTION__LANGUAGE;

  /**
   * The feature id for the '<em><b>Projects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTS__PROJECTS = SECTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Projects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTS_FEATURE_COUNT = SECTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.ProjectImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getProject()
   * @generated
   */
  int PROJECT = 7;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Technologies</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TECHNOLOGIES = 2;

  /**
   * The feature id for the '<em><b>Link</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__LINK = 3;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TAGS = 4;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.EducationImpl <em>Education</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.EducationImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getEducation()
   * @generated
   */
  int EDUCATION = 8;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDUCATION__LANGUAGE = SECTION__LANGUAGE;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDUCATION__DEGREES = SECTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Education</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDUCATION_FEATURE_COUNT = SECTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.DegreeImpl <em>Degree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.DegreeImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getDegree()
   * @generated
   */
  int DEGREE = 9;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE__TITLE = 0;

  /**
   * The feature id for the '<em><b>Institution</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE__INSTITUTION = 1;

  /**
   * The feature id for the '<em><b>Graduation Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE__GRADUATION_DATE = 2;

  /**
   * The feature id for the '<em><b>Country</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE__COUNTRY = 3;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE__TAGS = 4;

  /**
   * The number of structural features of the '<em>Degree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.SkillsImpl <em>Skills</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.SkillsImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSkills()
   * @generated
   */
  int SKILLS = 10;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKILLS__LANGUAGE = SECTION__LANGUAGE;

  /**
   * The feature id for the '<em><b>Skills</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKILLS__SKILLS = SECTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Skills</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKILLS_FEATURE_COUNT = SECTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.SkillImpl <em>Skill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.SkillImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSkill()
   * @generated
   */
  int SKILL = 11;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKILL__TITLE = 0;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKILL__TAGS = 1;

  /**
   * The number of structural features of the '<em>Skill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKILL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.InterestsImpl <em>Interests</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.InterestsImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getInterests()
   * @generated
   */
  int INTERESTS = 12;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERESTS__LANGUAGE = SECTION__LANGUAGE;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERESTS__TAGS = SECTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Interests</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERESTS_FEATURE_COUNT = SECTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.LanguagesImpl <em>Languages</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.LanguagesImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getLanguages()
   * @generated
   */
  int LANGUAGES = 13;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGES__LANGUAGE = SECTION__LANGUAGE;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGES__TAGS = SECTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Languages</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGES_FEATURE_COUNT = SECTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.MetricsImpl <em>Metrics</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.MetricsImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getMetrics()
   * @generated
   */
  int METRICS = 14;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRICS__LANGUAGE = SECTION__LANGUAGE;

  /**
   * The feature id for the '<em><b>Metrics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRICS__METRICS = SECTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Metrics</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRICS_FEATURE_COUNT = SECTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.MetricImpl <em>Metric</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.MetricImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getMetric()
   * @generated
   */
  int METRIC = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC__NAME = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Metric</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.ExpressionImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 16;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.CustomizationImpl <em>Customization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.CustomizationImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getCustomization()
   * @generated
   */
  int CUSTOMIZATION = 17;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZATION__LANGUAGE = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZATION__RULES = 1;

  /**
   * The number of structural features of the '<em>Customization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.RuleImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getRule()
   * @generated
   */
  int RULE = 18;

  /**
   * The feature id for the '<em><b>Section Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__SECTION_TYPE = 0;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__FILTER = 1;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.FilterImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getFilter()
   * @generated
   */
  int FILTER = 19;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.GeneralFilterImpl <em>General Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.GeneralFilterImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getGeneralFilter()
   * @generated
   */
  int GENERAL_FILTER = 20;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_FILTER__TAG = FILTER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>General Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.TemporalFilterImpl <em>Temporal Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.TemporalFilterImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getTemporalFilter()
   * @generated
   */
  int TEMPORAL_FILTER = 21;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPORAL_FILTER__START_DATE = FILTER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPORAL_FILTER__END_DATE = FILTER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Temporal Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPORAL_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.AllFilterImpl <em>All Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.AllFilterImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getAllFilter()
   * @generated
   */
  int ALL_FILTER = 22;

  /**
   * The number of structural features of the '<em>All Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.StringListImpl <em>String List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.StringListImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getStringList()
   * @generated
   */
  int STRING_LIST = 23;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LIST__VALUES = 0;

  /**
   * The number of structural features of the '<em>String List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.SubtractionImpl <em>Subtraction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.SubtractionImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSubtraction()
   * @generated
   */
  int SUBTRACTION = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACTION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACTION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Subtraction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACTION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.impl.NumberLiteralImpl
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 25;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.resume.resume.SectionType <em>Section Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.resume.resume.SectionType
   * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSectionType()
   * @generated
   */
  int SECTION_TYPE = 26;


  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Profile <em>Profile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Profile</em>'.
   * @see org.xtext.example.resume.resume.Profile
   * @generated
   */
  EClass getProfile();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Profile#getMetadata <em>Metadata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Metadata</em>'.
   * @see org.xtext.example.resume.resume.Profile#getMetadata()
   * @see #getProfile()
   * @generated
   */
  EReference getProfile_Metadata();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Profile#getUserdata <em>Userdata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Userdata</em>'.
   * @see org.xtext.example.resume.resume.Profile#getUserdata()
   * @see #getProfile()
   * @generated
   */
  EReference getProfile_Userdata();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.resume.resume.Profile#getSections <em>Sections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sections</em>'.
   * @see org.xtext.example.resume.resume.Profile#getSections()
   * @see #getProfile()
   * @generated
   */
  EReference getProfile_Sections();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Profile#getCustomization <em>Customization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Customization</em>'.
   * @see org.xtext.example.resume.resume.Profile#getCustomization()
   * @see #getProfile()
   * @generated
   */
  EReference getProfile_Customization();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Metadata <em>Metadata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metadata</em>'.
   * @see org.xtext.example.resume.resume.Metadata
   * @generated
   */
  EClass getMetadata();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Metadata#getStyle <em>Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Style</em>'.
   * @see org.xtext.example.resume.resume.Metadata#getStyle()
   * @see #getMetadata()
   * @generated
   */
  EAttribute getMetadata_Style();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Metadata#getFont <em>Font</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Font</em>'.
   * @see org.xtext.example.resume.resume.Metadata#getFont()
   * @see #getMetadata()
   * @generated
   */
  EAttribute getMetadata_Font();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Metadata#getImgPath <em>Img Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Img Path</em>'.
   * @see org.xtext.example.resume.resume.Metadata#getImgPath()
   * @see #getMetadata()
   * @generated
   */
  EAttribute getMetadata_ImgPath();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Userdata <em>Userdata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Userdata</em>'.
   * @see org.xtext.example.resume.resume.Userdata
   * @generated
   */
  EClass getUserdata();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Userdata#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.resume.resume.Userdata#getName()
   * @see #getUserdata()
   * @generated
   */
  EAttribute getUserdata_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Userdata#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.xtext.example.resume.resume.Userdata#getEmail()
   * @see #getUserdata()
   * @generated
   */
  EAttribute getUserdata_Email();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Userdata#getTelephoneNumber <em>Telephone Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Telephone Number</em>'.
   * @see org.xtext.example.resume.resume.Userdata#getTelephoneNumber()
   * @see #getUserdata()
   * @generated
   */
  EAttribute getUserdata_TelephoneNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Userdata#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see org.xtext.example.resume.resume.Userdata#getDirection()
   * @see #getUserdata()
   * @generated
   */
  EAttribute getUserdata_Direction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Userdata#getCity <em>City</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>City</em>'.
   * @see org.xtext.example.resume.resume.Userdata#getCity()
   * @see #getUserdata()
   * @generated
   */
  EAttribute getUserdata_City();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Userdata#getCountry <em>Country</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Country</em>'.
   * @see org.xtext.example.resume.resume.Userdata#getCountry()
   * @see #getUserdata()
   * @generated
   */
  EAttribute getUserdata_Country();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Section <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section</em>'.
   * @see org.xtext.example.resume.resume.Section
   * @generated
   */
  EClass getSection();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Section#getLanguage <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Language</em>'.
   * @see org.xtext.example.resume.resume.Section#getLanguage()
   * @see #getSection()
   * @generated
   */
  EAttribute getSection_Language();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Experience <em>Experience</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Experience</em>'.
   * @see org.xtext.example.resume.resume.Experience
   * @generated
   */
  EClass getExperience();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.resume.resume.Experience#getJobs <em>Jobs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Jobs</em>'.
   * @see org.xtext.example.resume.resume.Experience#getJobs()
   * @see #getExperience()
   * @generated
   */
  EReference getExperience_Jobs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Job <em>Job</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Job</em>'.
   * @see org.xtext.example.resume.resume.Job
   * @generated
   */
  EClass getJob();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Job#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.example.resume.resume.Job#getTitle()
   * @see #getJob()
   * @generated
   */
  EAttribute getJob_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Job#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.resume.resume.Job#getDescription()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Job#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Company</em>'.
   * @see org.xtext.example.resume.resume.Job#getCompany()
   * @see #getJob()
   * @generated
   */
  EAttribute getJob_Company();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Job#getStartDate <em>Start Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Date</em>'.
   * @see org.xtext.example.resume.resume.Job#getStartDate()
   * @see #getJob()
   * @generated
   */
  EAttribute getJob_StartDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Job#getEndDate <em>End Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Date</em>'.
   * @see org.xtext.example.resume.resume.Job#getEndDate()
   * @see #getJob()
   * @generated
   */
  EAttribute getJob_EndDate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Job#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tags</em>'.
   * @see org.xtext.example.resume.resume.Job#getTags()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Tags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Projects <em>Projects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Projects</em>'.
   * @see org.xtext.example.resume.resume.Projects
   * @generated
   */
  EClass getProjects();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.resume.resume.Projects#getProjects <em>Projects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Projects</em>'.
   * @see org.xtext.example.resume.resume.Projects#getProjects()
   * @see #getProjects()
   * @generated
   */
  EReference getProjects_Projects();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see org.xtext.example.resume.resume.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Project#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.example.resume.resume.Project#getTitle()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Project#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.resume.resume.Project#getDescription()
   * @see #getProject()
   * @generated
   */
  EReference getProject_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Project#getTechnologies <em>Technologies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Technologies</em>'.
   * @see org.xtext.example.resume.resume.Project#getTechnologies()
   * @see #getProject()
   * @generated
   */
  EReference getProject_Technologies();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Project#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link</em>'.
   * @see org.xtext.example.resume.resume.Project#getLink()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Link();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Project#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tags</em>'.
   * @see org.xtext.example.resume.resume.Project#getTags()
   * @see #getProject()
   * @generated
   */
  EReference getProject_Tags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Education <em>Education</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Education</em>'.
   * @see org.xtext.example.resume.resume.Education
   * @generated
   */
  EClass getEducation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.resume.resume.Education#getDegrees <em>Degrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Degrees</em>'.
   * @see org.xtext.example.resume.resume.Education#getDegrees()
   * @see #getEducation()
   * @generated
   */
  EReference getEducation_Degrees();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Degree <em>Degree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Degree</em>'.
   * @see org.xtext.example.resume.resume.Degree
   * @generated
   */
  EClass getDegree();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Degree#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.example.resume.resume.Degree#getTitle()
   * @see #getDegree()
   * @generated
   */
  EAttribute getDegree_Title();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Degree#getInstitution <em>Institution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Institution</em>'.
   * @see org.xtext.example.resume.resume.Degree#getInstitution()
   * @see #getDegree()
   * @generated
   */
  EAttribute getDegree_Institution();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Degree#getGraduationDate <em>Graduation Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Graduation Date</em>'.
   * @see org.xtext.example.resume.resume.Degree#getGraduationDate()
   * @see #getDegree()
   * @generated
   */
  EAttribute getDegree_GraduationDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Degree#getCountry <em>Country</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Country</em>'.
   * @see org.xtext.example.resume.resume.Degree#getCountry()
   * @see #getDegree()
   * @generated
   */
  EAttribute getDegree_Country();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Degree#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tags</em>'.
   * @see org.xtext.example.resume.resume.Degree#getTags()
   * @see #getDegree()
   * @generated
   */
  EReference getDegree_Tags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Skills <em>Skills</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Skills</em>'.
   * @see org.xtext.example.resume.resume.Skills
   * @generated
   */
  EClass getSkills();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.resume.resume.Skills#getSkills <em>Skills</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Skills</em>'.
   * @see org.xtext.example.resume.resume.Skills#getSkills()
   * @see #getSkills()
   * @generated
   */
  EReference getSkills_Skills();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Skill <em>Skill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Skill</em>'.
   * @see org.xtext.example.resume.resume.Skill
   * @generated
   */
  EClass getSkill();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Skill#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.example.resume.resume.Skill#getTitle()
   * @see #getSkill()
   * @generated
   */
  EAttribute getSkill_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Skill#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tags</em>'.
   * @see org.xtext.example.resume.resume.Skill#getTags()
   * @see #getSkill()
   * @generated
   */
  EReference getSkill_Tags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Interests <em>Interests</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interests</em>'.
   * @see org.xtext.example.resume.resume.Interests
   * @generated
   */
  EClass getInterests();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Interests#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tags</em>'.
   * @see org.xtext.example.resume.resume.Interests#getTags()
   * @see #getInterests()
   * @generated
   */
  EReference getInterests_Tags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Languages <em>Languages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Languages</em>'.
   * @see org.xtext.example.resume.resume.Languages
   * @generated
   */
  EClass getLanguages();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Languages#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tags</em>'.
   * @see org.xtext.example.resume.resume.Languages#getTags()
   * @see #getLanguages()
   * @generated
   */
  EReference getLanguages_Tags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Metrics <em>Metrics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metrics</em>'.
   * @see org.xtext.example.resume.resume.Metrics
   * @generated
   */
  EClass getMetrics();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.resume.resume.Metrics#getMetrics <em>Metrics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metrics</em>'.
   * @see org.xtext.example.resume.resume.Metrics#getMetrics()
   * @see #getMetrics()
   * @generated
   */
  EReference getMetrics_Metrics();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Metric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metric</em>'.
   * @see org.xtext.example.resume.resume.Metric
   * @generated
   */
  EClass getMetric();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Metric#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.resume.resume.Metric#getName()
   * @see #getMetric()
   * @generated
   */
  EAttribute getMetric_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Metric#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.xtext.example.resume.resume.Metric#getExpression()
   * @see #getMetric()
   * @generated
   */
  EReference getMetric_Expression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.resume.resume.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Customization <em>Customization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customization</em>'.
   * @see org.xtext.example.resume.resume.Customization
   * @generated
   */
  EClass getCustomization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Customization#getLanguage <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Language</em>'.
   * @see org.xtext.example.resume.resume.Customization#getLanguage()
   * @see #getCustomization()
   * @generated
   */
  EAttribute getCustomization_Language();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.resume.resume.Customization#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see org.xtext.example.resume.resume.Customization#getRules()
   * @see #getCustomization()
   * @generated
   */
  EReference getCustomization_Rules();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.example.resume.resume.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.Rule#getSectionType <em>Section Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Section Type</em>'.
   * @see org.xtext.example.resume.resume.Rule#getSectionType()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_SectionType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Rule#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.resume.resume.Rule#getFilter()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Filter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.xtext.example.resume.resume.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.GeneralFilter <em>General Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Filter</em>'.
   * @see org.xtext.example.resume.resume.GeneralFilter
   * @generated
   */
  EClass getGeneralFilter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.GeneralFilter#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see org.xtext.example.resume.resume.GeneralFilter#getTag()
   * @see #getGeneralFilter()
   * @generated
   */
  EAttribute getGeneralFilter_Tag();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.TemporalFilter <em>Temporal Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Temporal Filter</em>'.
   * @see org.xtext.example.resume.resume.TemporalFilter
   * @generated
   */
  EClass getTemporalFilter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.TemporalFilter#getStartDate <em>Start Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Date</em>'.
   * @see org.xtext.example.resume.resume.TemporalFilter#getStartDate()
   * @see #getTemporalFilter()
   * @generated
   */
  EAttribute getTemporalFilter_StartDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.TemporalFilter#getEndDate <em>End Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Date</em>'.
   * @see org.xtext.example.resume.resume.TemporalFilter#getEndDate()
   * @see #getTemporalFilter()
   * @generated
   */
  EAttribute getTemporalFilter_EndDate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.AllFilter <em>All Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Filter</em>'.
   * @see org.xtext.example.resume.resume.AllFilter
   * @generated
   */
  EClass getAllFilter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.StringList <em>String List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String List</em>'.
   * @see org.xtext.example.resume.resume.StringList
   * @generated
   */
  EClass getStringList();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.resume.resume.StringList#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.xtext.example.resume.resume.StringList#getValues()
   * @see #getStringList()
   * @generated
   */
  EAttribute getStringList_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.Subtraction <em>Subtraction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subtraction</em>'.
   * @see org.xtext.example.resume.resume.Subtraction
   * @generated
   */
  EClass getSubtraction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Subtraction#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.resume.resume.Subtraction#getLeft()
   * @see #getSubtraction()
   * @generated
   */
  EReference getSubtraction_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.resume.resume.Subtraction#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.resume.resume.Subtraction#getRight()
   * @see #getSubtraction()
   * @generated
   */
  EReference getSubtraction_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.resume.resume.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see org.xtext.example.resume.resume.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.resume.resume.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.resume.resume.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.resume.resume.SectionType <em>Section Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Section Type</em>'.
   * @see org.xtext.example.resume.resume.SectionType
   * @generated
   */
  EEnum getSectionType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ResumeFactory getResumeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.ProfileImpl <em>Profile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.ProfileImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getProfile()
     * @generated
     */
    EClass PROFILE = eINSTANCE.getProfile();

    /**
     * The meta object literal for the '<em><b>Metadata</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROFILE__METADATA = eINSTANCE.getProfile_Metadata();

    /**
     * The meta object literal for the '<em><b>Userdata</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROFILE__USERDATA = eINSTANCE.getProfile_Userdata();

    /**
     * The meta object literal for the '<em><b>Sections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROFILE__SECTIONS = eINSTANCE.getProfile_Sections();

    /**
     * The meta object literal for the '<em><b>Customization</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROFILE__CUSTOMIZATION = eINSTANCE.getProfile_Customization();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.MetadataImpl <em>Metadata</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.MetadataImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getMetadata()
     * @generated
     */
    EClass METADATA = eINSTANCE.getMetadata();

    /**
     * The meta object literal for the '<em><b>Style</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METADATA__STYLE = eINSTANCE.getMetadata_Style();

    /**
     * The meta object literal for the '<em><b>Font</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METADATA__FONT = eINSTANCE.getMetadata_Font();

    /**
     * The meta object literal for the '<em><b>Img Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METADATA__IMG_PATH = eINSTANCE.getMetadata_ImgPath();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.UserdataImpl <em>Userdata</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.UserdataImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getUserdata()
     * @generated
     */
    EClass USERDATA = eINSTANCE.getUserdata();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USERDATA__NAME = eINSTANCE.getUserdata_Name();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USERDATA__EMAIL = eINSTANCE.getUserdata_Email();

    /**
     * The meta object literal for the '<em><b>Telephone Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USERDATA__TELEPHONE_NUMBER = eINSTANCE.getUserdata_TelephoneNumber();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USERDATA__DIRECTION = eINSTANCE.getUserdata_Direction();

    /**
     * The meta object literal for the '<em><b>City</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USERDATA__CITY = eINSTANCE.getUserdata_City();

    /**
     * The meta object literal for the '<em><b>Country</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USERDATA__COUNTRY = eINSTANCE.getUserdata_Country();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.SectionImpl <em>Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.SectionImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSection()
     * @generated
     */
    EClass SECTION = eINSTANCE.getSection();

    /**
     * The meta object literal for the '<em><b>Language</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTION__LANGUAGE = eINSTANCE.getSection_Language();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.ExperienceImpl <em>Experience</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.ExperienceImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getExperience()
     * @generated
     */
    EClass EXPERIENCE = eINSTANCE.getExperience();

    /**
     * The meta object literal for the '<em><b>Jobs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPERIENCE__JOBS = eINSTANCE.getExperience_Jobs();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.JobImpl <em>Job</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.JobImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getJob()
     * @generated
     */
    EClass JOB = eINSTANCE.getJob();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOB__TITLE = eINSTANCE.getJob_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__DESCRIPTION = eINSTANCE.getJob_Description();

    /**
     * The meta object literal for the '<em><b>Company</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOB__COMPANY = eINSTANCE.getJob_Company();

    /**
     * The meta object literal for the '<em><b>Start Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOB__START_DATE = eINSTANCE.getJob_StartDate();

    /**
     * The meta object literal for the '<em><b>End Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOB__END_DATE = eINSTANCE.getJob_EndDate();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__TAGS = eINSTANCE.getJob_Tags();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.ProjectsImpl <em>Projects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.ProjectsImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getProjects()
     * @generated
     */
    EClass PROJECTS = eINSTANCE.getProjects();

    /**
     * The meta object literal for the '<em><b>Projects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTS__PROJECTS = eINSTANCE.getProjects_Projects();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.ProjectImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__TITLE = eINSTANCE.getProject_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__DESCRIPTION = eINSTANCE.getProject_Description();

    /**
     * The meta object literal for the '<em><b>Technologies</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__TECHNOLOGIES = eINSTANCE.getProject_Technologies();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__LINK = eINSTANCE.getProject_Link();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__TAGS = eINSTANCE.getProject_Tags();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.EducationImpl <em>Education</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.EducationImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getEducation()
     * @generated
     */
    EClass EDUCATION = eINSTANCE.getEducation();

    /**
     * The meta object literal for the '<em><b>Degrees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDUCATION__DEGREES = eINSTANCE.getEducation_Degrees();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.DegreeImpl <em>Degree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.DegreeImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getDegree()
     * @generated
     */
    EClass DEGREE = eINSTANCE.getDegree();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEGREE__TITLE = eINSTANCE.getDegree_Title();

    /**
     * The meta object literal for the '<em><b>Institution</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEGREE__INSTITUTION = eINSTANCE.getDegree_Institution();

    /**
     * The meta object literal for the '<em><b>Graduation Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEGREE__GRADUATION_DATE = eINSTANCE.getDegree_GraduationDate();

    /**
     * The meta object literal for the '<em><b>Country</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEGREE__COUNTRY = eINSTANCE.getDegree_Country();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEGREE__TAGS = eINSTANCE.getDegree_Tags();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.SkillsImpl <em>Skills</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.SkillsImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSkills()
     * @generated
     */
    EClass SKILLS = eINSTANCE.getSkills();

    /**
     * The meta object literal for the '<em><b>Skills</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SKILLS__SKILLS = eINSTANCE.getSkills_Skills();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.SkillImpl <em>Skill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.SkillImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSkill()
     * @generated
     */
    EClass SKILL = eINSTANCE.getSkill();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SKILL__TITLE = eINSTANCE.getSkill_Title();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SKILL__TAGS = eINSTANCE.getSkill_Tags();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.InterestsImpl <em>Interests</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.InterestsImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getInterests()
     * @generated
     */
    EClass INTERESTS = eINSTANCE.getInterests();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERESTS__TAGS = eINSTANCE.getInterests_Tags();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.LanguagesImpl <em>Languages</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.LanguagesImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getLanguages()
     * @generated
     */
    EClass LANGUAGES = eINSTANCE.getLanguages();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LANGUAGES__TAGS = eINSTANCE.getLanguages_Tags();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.MetricsImpl <em>Metrics</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.MetricsImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getMetrics()
     * @generated
     */
    EClass METRICS = eINSTANCE.getMetrics();

    /**
     * The meta object literal for the '<em><b>Metrics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METRICS__METRICS = eINSTANCE.getMetrics_Metrics();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.MetricImpl <em>Metric</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.MetricImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getMetric()
     * @generated
     */
    EClass METRIC = eINSTANCE.getMetric();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC__NAME = eINSTANCE.getMetric_Name();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METRIC__EXPRESSION = eINSTANCE.getMetric_Expression();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.ExpressionImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.CustomizationImpl <em>Customization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.CustomizationImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getCustomization()
     * @generated
     */
    EClass CUSTOMIZATION = eINSTANCE.getCustomization();

    /**
     * The meta object literal for the '<em><b>Language</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTOMIZATION__LANGUAGE = eINSTANCE.getCustomization_Language();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOMIZATION__RULES = eINSTANCE.getCustomization_Rules();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.RuleImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Section Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__SECTION_TYPE = eINSTANCE.getRule_SectionType();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__FILTER = eINSTANCE.getRule_Filter();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.FilterImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.GeneralFilterImpl <em>General Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.GeneralFilterImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getGeneralFilter()
     * @generated
     */
    EClass GENERAL_FILTER = eINSTANCE.getGeneralFilter();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_FILTER__TAG = eINSTANCE.getGeneralFilter_Tag();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.TemporalFilterImpl <em>Temporal Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.TemporalFilterImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getTemporalFilter()
     * @generated
     */
    EClass TEMPORAL_FILTER = eINSTANCE.getTemporalFilter();

    /**
     * The meta object literal for the '<em><b>Start Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMPORAL_FILTER__START_DATE = eINSTANCE.getTemporalFilter_StartDate();

    /**
     * The meta object literal for the '<em><b>End Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMPORAL_FILTER__END_DATE = eINSTANCE.getTemporalFilter_EndDate();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.AllFilterImpl <em>All Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.AllFilterImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getAllFilter()
     * @generated
     */
    EClass ALL_FILTER = eINSTANCE.getAllFilter();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.StringListImpl <em>String List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.StringListImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getStringList()
     * @generated
     */
    EClass STRING_LIST = eINSTANCE.getStringList();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LIST__VALUES = eINSTANCE.getStringList_Values();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.SubtractionImpl <em>Subtraction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.SubtractionImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSubtraction()
     * @generated
     */
    EClass SUBTRACTION = eINSTANCE.getSubtraction();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTRACTION__LEFT = eINSTANCE.getSubtraction_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTRACTION__RIGHT = eINSTANCE.getSubtraction_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.impl.NumberLiteralImpl
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.resume.resume.SectionType <em>Section Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.resume.resume.SectionType
     * @see org.xtext.example.resume.resume.impl.ResumePackageImpl#getSectionType()
     * @generated
     */
    EEnum SECTION_TYPE = eINSTANCE.getSectionType();

  }

} //ResumePackage
