/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Section Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.resume.resume.ResumePackage#getSectionType()
 * @model
 * @generated
 */
public enum SectionType implements Enumerator
{
  /**
   * The '<em><b>EXPERIENCE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXPERIENCE_VALUE
   * @generated
   * @ordered
   */
  EXPERIENCE(0, "EXPERIENCE", "Experience"),

  /**
   * The '<em><b>PROJECTS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROJECTS_VALUE
   * @generated
   * @ordered
   */
  PROJECTS(1, "PROJECTS", "Projects"),

  /**
   * The '<em><b>EDUCATION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EDUCATION_VALUE
   * @generated
   * @ordered
   */
  EDUCATION(2, "EDUCATION", "Education"),

  /**
   * The '<em><b>SKILLS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SKILLS_VALUE
   * @generated
   * @ordered
   */
  SKILLS(3, "SKILLS", "Skills"),

  /**
   * The '<em><b>INTERESTS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERESTS_VALUE
   * @generated
   * @ordered
   */
  INTERESTS(4, "INTERESTS", "Interests"),

  /**
   * The '<em><b>LANGUAGES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LANGUAGES_VALUE
   * @generated
   * @ordered
   */
  LANGUAGES(5, "LANGUAGES", "Languages"),

  /**
   * The '<em><b>METRICS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #METRICS_VALUE
   * @generated
   * @ordered
   */
  METRICS(6, "METRICS", "Metrics");

  /**
   * The '<em><b>EXPERIENCE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXPERIENCE
   * @model literal="Experience"
   * @generated
   * @ordered
   */
  public static final int EXPERIENCE_VALUE = 0;

  /**
   * The '<em><b>PROJECTS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROJECTS
   * @model literal="Projects"
   * @generated
   * @ordered
   */
  public static final int PROJECTS_VALUE = 1;

  /**
   * The '<em><b>EDUCATION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EDUCATION
   * @model literal="Education"
   * @generated
   * @ordered
   */
  public static final int EDUCATION_VALUE = 2;

  /**
   * The '<em><b>SKILLS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SKILLS
   * @model literal="Skills"
   * @generated
   * @ordered
   */
  public static final int SKILLS_VALUE = 3;

  /**
   * The '<em><b>INTERESTS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERESTS
   * @model literal="Interests"
   * @generated
   * @ordered
   */
  public static final int INTERESTS_VALUE = 4;

  /**
   * The '<em><b>LANGUAGES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LANGUAGES
   * @model literal="Languages"
   * @generated
   * @ordered
   */
  public static final int LANGUAGES_VALUE = 5;

  /**
   * The '<em><b>METRICS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #METRICS
   * @model literal="Metrics"
   * @generated
   * @ordered
   */
  public static final int METRICS_VALUE = 6;

  /**
   * An array of all the '<em><b>Section Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SectionType[] VALUES_ARRAY =
    new SectionType[]
    {
      EXPERIENCE,
      PROJECTS,
      EDUCATION,
      SKILLS,
      INTERESTS,
      LANGUAGES,
      METRICS,
    };

  /**
   * A public read-only list of all the '<em><b>Section Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SectionType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Section Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SectionType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SectionType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Section Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SectionType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SectionType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Section Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SectionType get(int value)
  {
    switch (value)
    {
      case EXPERIENCE_VALUE: return EXPERIENCE;
      case PROJECTS_VALUE: return PROJECTS;
      case EDUCATION_VALUE: return EDUCATION;
      case SKILLS_VALUE: return SKILLS;
      case INTERESTS_VALUE: return INTERESTS;
      case LANGUAGES_VALUE: return LANGUAGES;
      case METRICS_VALUE: return METRICS;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SectionType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SectionType
