/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skills</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Skills#getSkills <em>Skills</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getSkills()
 * @model
 * @generated
 */
public interface Skills extends Section
{
  /**
   * Returns the value of the '<em><b>Skills</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.resume.resume.Skill}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Skills</em>' containment reference list.
   * @see org.xtext.example.resume.resume.ResumePackage#getSkills_Skills()
   * @model containment="true"
   * @generated
   */
  EList<Skill> getSkills();

} // Skills
