/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Temporal Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.TemporalFilter#getStartDate <em>Start Date</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.TemporalFilter#getEndDate <em>End Date</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getTemporalFilter()
 * @model
 * @generated
 */
public interface TemporalFilter extends Filter
{
  /**
   * Returns the value of the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Date</em>' attribute.
   * @see #setStartDate(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getTemporalFilter_StartDate()
   * @model
   * @generated
   */
  String getStartDate();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.TemporalFilter#getStartDate <em>Start Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Date</em>' attribute.
   * @see #getStartDate()
   * @generated
   */
  void setStartDate(String value);

  /**
   * Returns the value of the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Date</em>' attribute.
   * @see #setEndDate(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getTemporalFilter_EndDate()
   * @model
   * @generated
   */
  String getEndDate();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.TemporalFilter#getEndDate <em>End Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Date</em>' attribute.
   * @see #getEndDate()
   * @generated
   */
  void setEndDate(String value);

} // TemporalFilter
