/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.resume;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Userdata</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.Userdata#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Userdata#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Userdata#getTelephoneNumber <em>Telephone Number</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Userdata#getDirection <em>Direction</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Userdata#getCity <em>City</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.Userdata#getCountry <em>Country</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.resume.resume.ResumePackage#getUserdata()
 * @model
 * @generated
 */
public interface Userdata extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getUserdata_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Userdata#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getUserdata_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Userdata#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Telephone Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Telephone Number</em>' attribute.
   * @see #setTelephoneNumber(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getUserdata_TelephoneNumber()
   * @model
   * @generated
   */
  String getTelephoneNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Userdata#getTelephoneNumber <em>Telephone Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Telephone Number</em>' attribute.
   * @see #getTelephoneNumber()
   * @generated
   */
  void setTelephoneNumber(String value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see #setDirection(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getUserdata_Direction()
   * @model
   * @generated
   */
  String getDirection();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Userdata#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see #getDirection()
   * @generated
   */
  void setDirection(String value);

  /**
   * Returns the value of the '<em><b>City</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>City</em>' attribute.
   * @see #setCity(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getUserdata_City()
   * @model
   * @generated
   */
  String getCity();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Userdata#getCity <em>City</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>City</em>' attribute.
   * @see #getCity()
   * @generated
   */
  void setCity(String value);

  /**
   * Returns the value of the '<em><b>Country</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Country</em>' attribute.
   * @see #setCountry(String)
   * @see org.xtext.example.resume.resume.ResumePackage#getUserdata_Country()
   * @model
   * @generated
   */
  String getCountry();

  /**
   * Sets the value of the '{@link org.xtext.example.resume.resume.Userdata#getCountry <em>Country</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Country</em>' attribute.
   * @see #getCountry()
   * @generated
   */
  void setCountry(String value);

} // Userdata
