/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ResumeUiModule extends AbstractResumeUiModule {

	public ResumeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
