/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractResumeScopeProvider extends DelegatingScopeProvider {
}
