/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ResumeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProfileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Profile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMetadataAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMetadataMetadataParserRuleCall_0_0 = (RuleCall)cMetadataAssignment_0.eContents().get(0);
		private final Assignment cUserdataAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUserdataUserdataParserRuleCall_1_0 = (RuleCall)cUserdataAssignment_1.eContents().get(0);
		private final Assignment cSectionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSectionsSectionParserRuleCall_2_0 = (RuleCall)cSectionsAssignment_2.eContents().get(0);
		private final Assignment cCustomizationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCustomizationCustomizationParserRuleCall_3_0 = (RuleCall)cCustomizationAssignment_3.eContents().get(0);
		
		//Profile:
		//    metadata=Metadata
		//    userdata=Userdata
		//    sections+=Section+
		//    customization=Customization
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//metadata=Metadata
		//userdata=Userdata
		//sections+=Section+
		//customization=Customization
		public Group getGroup() { return cGroup; }
		
		//metadata=Metadata
		public Assignment getMetadataAssignment_0() { return cMetadataAssignment_0; }
		
		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_0_0() { return cMetadataMetadataParserRuleCall_0_0; }
		
		//userdata=Userdata
		public Assignment getUserdataAssignment_1() { return cUserdataAssignment_1; }
		
		//Userdata
		public RuleCall getUserdataUserdataParserRuleCall_1_0() { return cUserdataUserdataParserRuleCall_1_0; }
		
		//sections+=Section+
		public Assignment getSectionsAssignment_2() { return cSectionsAssignment_2; }
		
		//Section
		public RuleCall getSectionsSectionParserRuleCall_2_0() { return cSectionsSectionParserRuleCall_2_0; }
		
		//customization=Customization
		public Assignment getCustomizationAssignment_3() { return cCustomizationAssignment_3; }
		
		//Customization
		public RuleCall getCustomizationCustomizationParserRuleCall_3_0() { return cCustomizationCustomizationParserRuleCall_3_0; }
	}
	public class MetadataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Metadata");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMetadataKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cStyleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStyleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStyleSTRINGTerminalRuleCall_2_0 = (RuleCall)cStyleAssignment_2.eContents().get(0);
		private final Keyword cFontKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFontAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFontSTRINGTerminalRuleCall_4_0 = (RuleCall)cFontAssignment_4.eContents().get(0);
		private final Keyword cImgPathKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cImgPathAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cImgPathSTRINGTerminalRuleCall_6_0 = (RuleCall)cImgPathAssignment_6.eContents().get(0);
		
		//Metadata:
		//    'Metadata' 'style:' style=STRING 'font:' font=STRING 'imgPath:' imgPath=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Metadata' 'style:' style=STRING 'font:' font=STRING 'imgPath:' imgPath=STRING
		public Group getGroup() { return cGroup; }
		
		//'Metadata'
		public Keyword getMetadataKeyword_0() { return cMetadataKeyword_0; }
		
		//'style:'
		public Keyword getStyleKeyword_1() { return cStyleKeyword_1; }
		
		//style=STRING
		public Assignment getStyleAssignment_2() { return cStyleAssignment_2; }
		
		//STRING
		public RuleCall getStyleSTRINGTerminalRuleCall_2_0() { return cStyleSTRINGTerminalRuleCall_2_0; }
		
		//'font:'
		public Keyword getFontKeyword_3() { return cFontKeyword_3; }
		
		//font=STRING
		public Assignment getFontAssignment_4() { return cFontAssignment_4; }
		
		//STRING
		public RuleCall getFontSTRINGTerminalRuleCall_4_0() { return cFontSTRINGTerminalRuleCall_4_0; }
		
		//'imgPath:'
		public Keyword getImgPathKeyword_5() { return cImgPathKeyword_5; }
		
		//imgPath=STRING
		public Assignment getImgPathAssignment_6() { return cImgPathAssignment_6; }
		
		//STRING
		public RuleCall getImgPathSTRINGTerminalRuleCall_6_0() { return cImgPathSTRINGTerminalRuleCall_6_0; }
	}
	public class UserdataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Userdata");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserdataKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEmailKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEmailAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEmailSTRINGTerminalRuleCall_4_0 = (RuleCall)cEmailAssignment_4.eContents().get(0);
		private final Keyword cTelephoneNumberKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTelephoneNumberAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTelephoneNumberSTRINGTerminalRuleCall_6_0 = (RuleCall)cTelephoneNumberAssignment_6.eContents().get(0);
		private final Keyword cDirectionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDirectionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDirectionSTRINGTerminalRuleCall_8_0 = (RuleCall)cDirectionAssignment_8.eContents().get(0);
		private final Keyword cCityKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCityAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cCitySTRINGTerminalRuleCall_10_0 = (RuleCall)cCityAssignment_10.eContents().get(0);
		private final Keyword cCountryKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cCountryAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cCountrySTRINGTerminalRuleCall_12_0 = (RuleCall)cCountryAssignment_12.eContents().get(0);
		
		//Userdata:
		//    'Userdata' 'name:' name=STRING 'email:' email=STRING 'telephoneNumber:' telephoneNumber=STRING 'direction:' direction=STRING 'city:' city=STRING 'country:' country=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Userdata' 'name:' name=STRING 'email:' email=STRING 'telephoneNumber:' telephoneNumber=STRING 'direction:' direction=STRING 'city:' city=STRING 'country:' country=STRING
		public Group getGroup() { return cGroup; }
		
		//'Userdata'
		public Keyword getUserdataKeyword_0() { return cUserdataKeyword_0; }
		
		//'name:'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//'email:'
		public Keyword getEmailKeyword_3() { return cEmailKeyword_3; }
		
		//email=STRING
		public Assignment getEmailAssignment_4() { return cEmailAssignment_4; }
		
		//STRING
		public RuleCall getEmailSTRINGTerminalRuleCall_4_0() { return cEmailSTRINGTerminalRuleCall_4_0; }
		
		//'telephoneNumber:'
		public Keyword getTelephoneNumberKeyword_5() { return cTelephoneNumberKeyword_5; }
		
		//telephoneNumber=STRING
		public Assignment getTelephoneNumberAssignment_6() { return cTelephoneNumberAssignment_6; }
		
		//STRING
		public RuleCall getTelephoneNumberSTRINGTerminalRuleCall_6_0() { return cTelephoneNumberSTRINGTerminalRuleCall_6_0; }
		
		//'direction:'
		public Keyword getDirectionKeyword_7() { return cDirectionKeyword_7; }
		
		//direction=STRING
		public Assignment getDirectionAssignment_8() { return cDirectionAssignment_8; }
		
		//STRING
		public RuleCall getDirectionSTRINGTerminalRuleCall_8_0() { return cDirectionSTRINGTerminalRuleCall_8_0; }
		
		//'city:'
		public Keyword getCityKeyword_9() { return cCityKeyword_9; }
		
		//city=STRING
		public Assignment getCityAssignment_10() { return cCityAssignment_10; }
		
		//STRING
		public RuleCall getCitySTRINGTerminalRuleCall_10_0() { return cCitySTRINGTerminalRuleCall_10_0; }
		
		//'country:'
		public Keyword getCountryKeyword_11() { return cCountryKeyword_11; }
		
		//country=STRING
		public Assignment getCountryAssignment_12() { return cCountryAssignment_12; }
		
		//STRING
		public RuleCall getCountrySTRINGTerminalRuleCall_12_0() { return cCountrySTRINGTerminalRuleCall_12_0; }
	}
	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Section");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExperienceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cProjectsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEducationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSkillsParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cInterestsParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cLanguagesParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cMetricsParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Section:
		//    Experience | Projects | Education | Skills | Interests | Languages | Metrics
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Experience | Projects | Education | Skills | Interests | Languages | Metrics
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Experience
		public RuleCall getExperienceParserRuleCall_0() { return cExperienceParserRuleCall_0; }
		
		//Projects
		public RuleCall getProjectsParserRuleCall_1() { return cProjectsParserRuleCall_1; }
		
		//Education
		public RuleCall getEducationParserRuleCall_2() { return cEducationParserRuleCall_2; }
		
		//Skills
		public RuleCall getSkillsParserRuleCall_3() { return cSkillsParserRuleCall_3; }
		
		//Interests
		public RuleCall getInterestsParserRuleCall_4() { return cInterestsParserRuleCall_4; }
		
		//Languages
		public RuleCall getLanguagesParserRuleCall_5() { return cLanguagesParserRuleCall_5; }
		
		//Metrics
		public RuleCall getMetricsParserRuleCall_6() { return cMetricsParserRuleCall_6; }
	}
	public class ExperienceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Experience");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExperienceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Assignment cJobsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cJobsJobParserRuleCall_3_0 = (RuleCall)cJobsAssignment_3.eContents().get(0);
		
		//Experience:
		//    'Experience' 'language:' language=STRING jobs+=Job+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Experience' 'language:' language=STRING jobs+=Job+
		public Group getGroup() { return cGroup; }
		
		//'Experience'
		public Keyword getExperienceKeyword_0() { return cExperienceKeyword_0; }
		
		//'language:'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//language=STRING
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_2_0() { return cLanguageSTRINGTerminalRuleCall_2_0; }
		
		//jobs+=Job+
		public Assignment getJobsAssignment_3() { return cJobsAssignment_3; }
		
		//Job
		public RuleCall getJobsJobParserRuleCall_3_0() { return cJobsJobParserRuleCall_3_0; }
	}
	public class JobElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Job");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cDescriptionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionStringListParserRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Keyword cCompanyKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCompanyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCompanySTRINGTerminalRuleCall_5_0 = (RuleCall)cCompanyAssignment_5.eContents().get(0);
		private final Keyword cStartDateKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStartDateAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStartDateDateParserRuleCall_7_0 = (RuleCall)cStartDateAssignment_7.eContents().get(0);
		private final Keyword cEndDateKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cEndDateAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cEndDateDateParserRuleCall_9_0 = (RuleCall)cEndDateAssignment_9.eContents().get(0);
		private final Keyword cTagsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cTagsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cTagsStringListParserRuleCall_11_0 = (RuleCall)cTagsAssignment_11.eContents().get(0);
		
		//Job:
		//    'title:' title=STRING
		//    'description:' description=StringList
		//    'company:' company=STRING
		//    'startDate:' startDate=Date
		//    'endDate:' endDate=Date
		//    'tags:' tags=StringList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'title:' title=STRING
		//'description:' description=StringList
		//'company:' company=STRING
		//'startDate:' startDate=Date
		//'endDate:' endDate=Date
		//'tags:' tags=StringList
		public Group getGroup() { return cGroup; }
		
		//'title:'
		public Keyword getTitleKeyword_0() { return cTitleKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//'description:'
		public Keyword getDescriptionKeyword_2() { return cDescriptionKeyword_2; }
		
		//description=StringList
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }
		
		//StringList
		public RuleCall getDescriptionStringListParserRuleCall_3_0() { return cDescriptionStringListParserRuleCall_3_0; }
		
		//'company:'
		public Keyword getCompanyKeyword_4() { return cCompanyKeyword_4; }
		
		//company=STRING
		public Assignment getCompanyAssignment_5() { return cCompanyAssignment_5; }
		
		//STRING
		public RuleCall getCompanySTRINGTerminalRuleCall_5_0() { return cCompanySTRINGTerminalRuleCall_5_0; }
		
		//'startDate:'
		public Keyword getStartDateKeyword_6() { return cStartDateKeyword_6; }
		
		//startDate=Date
		public Assignment getStartDateAssignment_7() { return cStartDateAssignment_7; }
		
		//Date
		public RuleCall getStartDateDateParserRuleCall_7_0() { return cStartDateDateParserRuleCall_7_0; }
		
		//'endDate:'
		public Keyword getEndDateKeyword_8() { return cEndDateKeyword_8; }
		
		//endDate=Date
		public Assignment getEndDateAssignment_9() { return cEndDateAssignment_9; }
		
		//Date
		public RuleCall getEndDateDateParserRuleCall_9_0() { return cEndDateDateParserRuleCall_9_0; }
		
		//'tags:'
		public Keyword getTagsKeyword_10() { return cTagsKeyword_10; }
		
		//tags=StringList
		public Assignment getTagsAssignment_11() { return cTagsAssignment_11; }
		
		//StringList
		public RuleCall getTagsStringListParserRuleCall_11_0() { return cTagsStringListParserRuleCall_11_0; }
	}
	public class ProjectsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Projects");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProjectsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Assignment cProjectsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProjectsProjectParserRuleCall_3_0 = (RuleCall)cProjectsAssignment_3.eContents().get(0);
		
		//Projects:
		//    'Projects' 'language:' language=STRING projects+=Project+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Projects' 'language:' language=STRING projects+=Project+
		public Group getGroup() { return cGroup; }
		
		//'Projects'
		public Keyword getProjectsKeyword_0() { return cProjectsKeyword_0; }
		
		//'language:'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//language=STRING
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_2_0() { return cLanguageSTRINGTerminalRuleCall_2_0; }
		
		//projects+=Project+
		public Assignment getProjectsAssignment_3() { return cProjectsAssignment_3; }
		
		//Project
		public RuleCall getProjectsProjectParserRuleCall_3_0() { return cProjectsProjectParserRuleCall_3_0; }
	}
	public class ProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Project");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cDescriptionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionStringListParserRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Keyword cTechnologiesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTechnologiesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTechnologiesStringListParserRuleCall_5_0 = (RuleCall)cTechnologiesAssignment_5.eContents().get(0);
		private final Keyword cLinkKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLinkAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLinkSTRINGTerminalRuleCall_7_0 = (RuleCall)cLinkAssignment_7.eContents().get(0);
		private final Keyword cTagsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTagsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTagsStringListParserRuleCall_9_0 = (RuleCall)cTagsAssignment_9.eContents().get(0);
		
		//Project:
		//    'title:' title=STRING
		//    'description:' description=StringList
		//    'technologies:' technologies=StringList
		//    'link:' link=STRING
		//    'tags:' tags=StringList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'title:' title=STRING
		//'description:' description=StringList
		//'technologies:' technologies=StringList
		//'link:' link=STRING
		//'tags:' tags=StringList
		public Group getGroup() { return cGroup; }
		
		//'title:'
		public Keyword getTitleKeyword_0() { return cTitleKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//'description:'
		public Keyword getDescriptionKeyword_2() { return cDescriptionKeyword_2; }
		
		//description=StringList
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }
		
		//StringList
		public RuleCall getDescriptionStringListParserRuleCall_3_0() { return cDescriptionStringListParserRuleCall_3_0; }
		
		//'technologies:'
		public Keyword getTechnologiesKeyword_4() { return cTechnologiesKeyword_4; }
		
		//technologies=StringList
		public Assignment getTechnologiesAssignment_5() { return cTechnologiesAssignment_5; }
		
		//StringList
		public RuleCall getTechnologiesStringListParserRuleCall_5_0() { return cTechnologiesStringListParserRuleCall_5_0; }
		
		//'link:'
		public Keyword getLinkKeyword_6() { return cLinkKeyword_6; }
		
		//link=STRING
		public Assignment getLinkAssignment_7() { return cLinkAssignment_7; }
		
		//STRING
		public RuleCall getLinkSTRINGTerminalRuleCall_7_0() { return cLinkSTRINGTerminalRuleCall_7_0; }
		
		//'tags:'
		public Keyword getTagsKeyword_8() { return cTagsKeyword_8; }
		
		//tags=StringList
		public Assignment getTagsAssignment_9() { return cTagsAssignment_9; }
		
		//StringList
		public RuleCall getTagsStringListParserRuleCall_9_0() { return cTagsStringListParserRuleCall_9_0; }
	}
	public class EducationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Education");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEducationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Assignment cDegreesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDegreesDegreeParserRuleCall_3_0 = (RuleCall)cDegreesAssignment_3.eContents().get(0);
		
		//Education:
		//    'Education' 'language:' language=STRING degrees+=Degree*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Education' 'language:' language=STRING degrees+=Degree*
		public Group getGroup() { return cGroup; }
		
		//'Education'
		public Keyword getEducationKeyword_0() { return cEducationKeyword_0; }
		
		//'language:'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//language=STRING
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_2_0() { return cLanguageSTRINGTerminalRuleCall_2_0; }
		
		//degrees+=Degree*
		public Assignment getDegreesAssignment_3() { return cDegreesAssignment_3; }
		
		//Degree
		public RuleCall getDegreesDegreeParserRuleCall_3_0() { return cDegreesDegreeParserRuleCall_3_0; }
	}
	public class DegreeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Degree");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cInstitutionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInstitutionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInstitutionSTRINGTerminalRuleCall_3_0 = (RuleCall)cInstitutionAssignment_3.eContents().get(0);
		private final Keyword cGraduationDateKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cGraduationDateAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cGraduationDateDateParserRuleCall_5_0 = (RuleCall)cGraduationDateAssignment_5.eContents().get(0);
		private final Keyword cCountryKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCountryAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCountrySTRINGTerminalRuleCall_7_0 = (RuleCall)cCountryAssignment_7.eContents().get(0);
		private final Keyword cTagsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTagsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTagsStringListParserRuleCall_9_0 = (RuleCall)cTagsAssignment_9.eContents().get(0);
		
		//Degree:
		//    'title:' title=STRING
		//    'institution:' institution=STRING
		//    'graduationDate:' graduationDate=Date
		//    'country:' country=STRING
		//    'tags:' tags=StringList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'title:' title=STRING
		//'institution:' institution=STRING
		//'graduationDate:' graduationDate=Date
		//'country:' country=STRING
		//'tags:' tags=StringList
		public Group getGroup() { return cGroup; }
		
		//'title:'
		public Keyword getTitleKeyword_0() { return cTitleKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//'institution:'
		public Keyword getInstitutionKeyword_2() { return cInstitutionKeyword_2; }
		
		//institution=STRING
		public Assignment getInstitutionAssignment_3() { return cInstitutionAssignment_3; }
		
		//STRING
		public RuleCall getInstitutionSTRINGTerminalRuleCall_3_0() { return cInstitutionSTRINGTerminalRuleCall_3_0; }
		
		//'graduationDate:'
		public Keyword getGraduationDateKeyword_4() { return cGraduationDateKeyword_4; }
		
		//graduationDate=Date
		public Assignment getGraduationDateAssignment_5() { return cGraduationDateAssignment_5; }
		
		//Date
		public RuleCall getGraduationDateDateParserRuleCall_5_0() { return cGraduationDateDateParserRuleCall_5_0; }
		
		//'country:'
		public Keyword getCountryKeyword_6() { return cCountryKeyword_6; }
		
		//country=STRING
		public Assignment getCountryAssignment_7() { return cCountryAssignment_7; }
		
		//STRING
		public RuleCall getCountrySTRINGTerminalRuleCall_7_0() { return cCountrySTRINGTerminalRuleCall_7_0; }
		
		//'tags:'
		public Keyword getTagsKeyword_8() { return cTagsKeyword_8; }
		
		//tags=StringList
		public Assignment getTagsAssignment_9() { return cTagsAssignment_9; }
		
		//StringList
		public RuleCall getTagsStringListParserRuleCall_9_0() { return cTagsStringListParserRuleCall_9_0; }
	}
	public class SkillsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Skills");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSkillsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Assignment cSkillsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSkillsSkillParserRuleCall_3_0 = (RuleCall)cSkillsAssignment_3.eContents().get(0);
		
		//Skills:
		//    'Skills' 'language:' language=STRING skills+=Skill+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Skills' 'language:' language=STRING skills+=Skill+
		public Group getGroup() { return cGroup; }
		
		//'Skills'
		public Keyword getSkillsKeyword_0() { return cSkillsKeyword_0; }
		
		//'language:'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//language=STRING
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_2_0() { return cLanguageSTRINGTerminalRuleCall_2_0; }
		
		//skills+=Skill+
		public Assignment getSkillsAssignment_3() { return cSkillsAssignment_3; }
		
		//Skill
		public RuleCall getSkillsSkillParserRuleCall_3_0() { return cSkillsSkillParserRuleCall_3_0; }
	}
	public class SkillElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Skill");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cTagsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTagsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTagsStringListParserRuleCall_3_0 = (RuleCall)cTagsAssignment_3.eContents().get(0);
		
		//Skill:
		//    'title:' title=STRING 'tags:' tags=StringList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'title:' title=STRING 'tags:' tags=StringList
		public Group getGroup() { return cGroup; }
		
		//'title:'
		public Keyword getTitleKeyword_0() { return cTitleKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//'tags:'
		public Keyword getTagsKeyword_2() { return cTagsKeyword_2; }
		
		//tags=StringList
		public Assignment getTagsAssignment_3() { return cTagsAssignment_3; }
		
		//StringList
		public RuleCall getTagsStringListParserRuleCall_3_0() { return cTagsStringListParserRuleCall_3_0; }
	}
	public class InterestsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Interests");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInterestsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Keyword cTagsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTagsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTagsStringListParserRuleCall_4_0 = (RuleCall)cTagsAssignment_4.eContents().get(0);
		
		//Interests:
		//    'Interests' 'language:' language=STRING 'tags:' tags=StringList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Interests' 'language:' language=STRING 'tags:' tags=StringList
		public Group getGroup() { return cGroup; }
		
		//'Interests'
		public Keyword getInterestsKeyword_0() { return cInterestsKeyword_0; }
		
		//'language:'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//language=STRING
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_2_0() { return cLanguageSTRINGTerminalRuleCall_2_0; }
		
		//'tags:'
		public Keyword getTagsKeyword_3() { return cTagsKeyword_3; }
		
		//tags=StringList
		public Assignment getTagsAssignment_4() { return cTagsAssignment_4; }
		
		//StringList
		public RuleCall getTagsStringListParserRuleCall_4_0() { return cTagsStringListParserRuleCall_4_0; }
	}
	public class LanguagesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Languages");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLanguagesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Keyword cTagsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTagsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTagsStringListParserRuleCall_4_0 = (RuleCall)cTagsAssignment_4.eContents().get(0);
		
		//Languages:
		//    'Languages' 'language:' language=STRING 'tags:' tags=StringList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Languages' 'language:' language=STRING 'tags:' tags=StringList
		public Group getGroup() { return cGroup; }
		
		//'Languages'
		public Keyword getLanguagesKeyword_0() { return cLanguagesKeyword_0; }
		
		//'language:'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//language=STRING
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_2_0() { return cLanguageSTRINGTerminalRuleCall_2_0; }
		
		//'tags:'
		public Keyword getTagsKeyword_3() { return cTagsKeyword_3; }
		
		//tags=StringList
		public Assignment getTagsAssignment_4() { return cTagsAssignment_4; }
		
		//StringList
		public RuleCall getTagsStringListParserRuleCall_4_0() { return cTagsStringListParserRuleCall_4_0; }
	}
	public class MetricsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Metrics");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMetricsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLanguageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Assignment cMetricsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMetricsMetricParserRuleCall_3_0 = (RuleCall)cMetricsAssignment_3.eContents().get(0);
		
		//Metrics:
		//    'Metrics' 'language:' language=STRING metrics+=Metric+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Metrics' 'language:' language=STRING metrics+=Metric+
		public Group getGroup() { return cGroup; }
		
		//'Metrics'
		public Keyword getMetricsKeyword_0() { return cMetricsKeyword_0; }
		
		//'language:'
		public Keyword getLanguageKeyword_1() { return cLanguageKeyword_1; }
		
		//language=STRING
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_2_0() { return cLanguageSTRINGTerminalRuleCall_2_0; }
		
		//metrics+=Metric+
		public Assignment getMetricsAssignment_3() { return cMetricsAssignment_3; }
		
		//Metric
		public RuleCall getMetricsMetricParserRuleCall_3_0() { return cMetricsMetricParserRuleCall_3_0; }
	}
	public class MetricElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Metric");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMetricKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		
		//Metric:
		//    'Metric' name=STRING '=' expression=Expression
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Metric' name=STRING '=' expression=Expression
		public Group getGroup() { return cGroup; }
		
		//'Metric'
		public Keyword getMetricKeyword_0() { return cMetricKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Expression");
		private final RuleCall cSubtractionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expression:
		//    Subtraction
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Subtraction
		public RuleCall getSubtractionParserRuleCall() { return cSubtractionParserRuleCall; }
	}
	public class SubtractionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Subtraction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNumberLiteralParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cSubtractionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightNumberLiteralParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Subtraction returns Expression:
		//    NumberLiteral (
		//        {Subtraction.left=current} '-' right=NumberLiteral
		//    )*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//NumberLiteral (
		//    {Subtraction.left=current} '-' right=NumberLiteral
		//)*
		public Group getGroup() { return cGroup; }
		
		//NumberLiteral
		public RuleCall getNumberLiteralParserRuleCall_0() { return cNumberLiteralParserRuleCall_0; }
		
		//(
		//       {Subtraction.left=current} '-' right=NumberLiteral
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Subtraction.left=current}
		public Action getSubtractionLeftAction_1_0() { return cSubtractionLeftAction_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_1() { return cHyphenMinusKeyword_1_1; }
		
		//right=NumberLiteral
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//NumberLiteral
		public RuleCall getRightNumberLiteralParserRuleCall_1_2_0() { return cRightNumberLiteralParserRuleCall_1_2_0; }
	}
	public class NumberLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.NumberLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNumberLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//NumberLiteral returns Expression:
		//    {NumberLiteral} value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{NumberLiteral} value=INT
		public Group getGroup() { return cGroup; }
		
		//{NumberLiteral}
		public Action getNumberLiteralAction_0() { return cNumberLiteralAction_0; }
		
		//value=INT
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_1_0() { return cValueINTTerminalRuleCall_1_0; }
	}
	public class CustomizationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Customization");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCustomizationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cIncludeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cProfileKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cWhereKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLanguageKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLanguageAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLanguageSTRINGTerminalRuleCall_5_0 = (RuleCall)cLanguageAssignment_5.eContents().get(0);
		private final Assignment cRulesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRulesRuleParserRuleCall_6_0 = (RuleCall)cRulesAssignment_6.eContents().get(0);
		
		//Customization:
		//    'Customization' 'include' 'Profile' 'where' 'language' language=STRING rules+=Rule*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Customization' 'include' 'Profile' 'where' 'language' language=STRING rules+=Rule*
		public Group getGroup() { return cGroup; }
		
		//'Customization'
		public Keyword getCustomizationKeyword_0() { return cCustomizationKeyword_0; }
		
		//'include'
		public Keyword getIncludeKeyword_1() { return cIncludeKeyword_1; }
		
		//'Profile'
		public Keyword getProfileKeyword_2() { return cProfileKeyword_2; }
		
		//'where'
		public Keyword getWhereKeyword_3() { return cWhereKeyword_3; }
		
		//'language'
		public Keyword getLanguageKeyword_4() { return cLanguageKeyword_4; }
		
		//language=STRING
		public Assignment getLanguageAssignment_5() { return cLanguageAssignment_5; }
		
		//STRING
		public RuleCall getLanguageSTRINGTerminalRuleCall_5_0() { return cLanguageSTRINGTerminalRuleCall_5_0; }
		
		//rules+=Rule*
		public Assignment getRulesAssignment_6() { return cRulesAssignment_6; }
		
		//Rule
		public RuleCall getRulesRuleParserRuleCall_6_0() { return cRulesRuleParserRuleCall_6_0; }
	}
	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIncludeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSectionTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSectionTypeSectionTypeEnumRuleCall_1_0 = (RuleCall)cSectionTypeAssignment_1.eContents().get(0);
		private final Keyword cWhereKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFilterAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFilterFilterParserRuleCall_3_0 = (RuleCall)cFilterAssignment_3.eContents().get(0);
		
		//Rule:
		//    'include' sectionType=SectionType 'where' filter=Filter
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'include' sectionType=SectionType 'where' filter=Filter
		public Group getGroup() { return cGroup; }
		
		//'include'
		public Keyword getIncludeKeyword_0() { return cIncludeKeyword_0; }
		
		//sectionType=SectionType
		public Assignment getSectionTypeAssignment_1() { return cSectionTypeAssignment_1; }
		
		//SectionType
		public RuleCall getSectionTypeSectionTypeEnumRuleCall_1_0() { return cSectionTypeSectionTypeEnumRuleCall_1_0; }
		
		//'where'
		public Keyword getWhereKeyword_2() { return cWhereKeyword_2; }
		
		//filter=Filter
		public Assignment getFilterAssignment_3() { return cFilterAssignment_3; }
		
		//Filter
		public RuleCall getFilterFilterParserRuleCall_3_0() { return cFilterFilterParserRuleCall_3_0; }
	}
	public class FilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Filter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGeneralFilterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTemporalFilterParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAllFilterParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Filter:
		//    GeneralFilter | TemporalFilter | AllFilter
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//GeneralFilter | TemporalFilter | AllFilter
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GeneralFilter
		public RuleCall getGeneralFilterParserRuleCall_0() { return cGeneralFilterParserRuleCall_0; }
		
		//TemporalFilter
		public RuleCall getTemporalFilterParserRuleCall_1() { return cTemporalFilterParserRuleCall_1; }
		
		//AllFilter
		public RuleCall getAllFilterParserRuleCall_2() { return cAllFilterParserRuleCall_2; }
	}
	public class GeneralFilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.GeneralFilter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTagsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cIncludeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTagAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTagSTRINGTerminalRuleCall_2_0 = (RuleCall)cTagAssignment_2.eContents().get(0);
		
		//GeneralFilter:
		//    'tags' 'include' tag=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'tags' 'include' tag=STRING
		public Group getGroup() { return cGroup; }
		
		//'tags'
		public Keyword getTagsKeyword_0() { return cTagsKeyword_0; }
		
		//'include'
		public Keyword getIncludeKeyword_1() { return cIncludeKeyword_1; }
		
		//tag=STRING
		public Assignment getTagAssignment_2() { return cTagAssignment_2; }
		
		//STRING
		public RuleCall getTagSTRINGTerminalRuleCall_2_0() { return cTagSTRINGTerminalRuleCall_2_0; }
	}
	public class TemporalFilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.TemporalFilter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cStartDateKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cAfterKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cStartDateAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cStartDateDateParserRuleCall_0_2_0 = (RuleCall)cStartDateAssignment_0_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cEndDateKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cBeforeKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cEndDateAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cEndDateDateParserRuleCall_1_2_0 = (RuleCall)cEndDateAssignment_1_2.eContents().get(0);
		
		//TemporalFilter:
		//    ('startDate' 'after' startDate=Date) | ('endDate' 'before' endDate=Date)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('startDate' 'after' startDate=Date) | ('endDate' 'before' endDate=Date)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//('startDate' 'after' startDate=Date)
		public Group getGroup_0() { return cGroup_0; }
		
		//'startDate'
		public Keyword getStartDateKeyword_0_0() { return cStartDateKeyword_0_0; }
		
		//'after'
		public Keyword getAfterKeyword_0_1() { return cAfterKeyword_0_1; }
		
		//startDate=Date
		public Assignment getStartDateAssignment_0_2() { return cStartDateAssignment_0_2; }
		
		//Date
		public RuleCall getStartDateDateParserRuleCall_0_2_0() { return cStartDateDateParserRuleCall_0_2_0; }
		
		//('endDate' 'before' endDate=Date)
		public Group getGroup_1() { return cGroup_1; }
		
		//'endDate'
		public Keyword getEndDateKeyword_1_0() { return cEndDateKeyword_1_0; }
		
		//'before'
		public Keyword getBeforeKeyword_1_1() { return cBeforeKeyword_1_1; }
		
		//endDate=Date
		public Assignment getEndDateAssignment_1_2() { return cEndDateAssignment_1_2; }
		
		//Date
		public RuleCall getEndDateDateParserRuleCall_1_2_0() { return cEndDateDateParserRuleCall_1_2_0; }
	}
	public class AllFilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.AllFilter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAllFilterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAllKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//AllFilter:
		//    {AllFilter} 'all'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{AllFilter} 'all'
		public Group getGroup() { return cGroup; }
		
		//{AllFilter}
		public Action getAllFilterAction_0() { return cAllFilterAction_0; }
		
		//'all'
		public Keyword getAllKeyword_1() { return cAllKeyword_1; }
	}
	public class StringListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.StringList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValuesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValuesSTRINGTerminalRuleCall_1_0 = (RuleCall)cValuesAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cValuesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cValuesSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cValuesAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//StringList:
		//    '[' values+=STRING (',' values+=STRING)* ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'[' values+=STRING (',' values+=STRING)* ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//values+=STRING
		public Assignment getValuesAssignment_1() { return cValuesAssignment_1; }
		
		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_1_0() { return cValuesSTRINGTerminalRuleCall_1_0; }
		
		//(',' values+=STRING)*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//values+=STRING
		public Assignment getValuesAssignment_2_1() { return cValuesAssignment_2_1; }
		
		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_2_1_0() { return cValuesSTRINGTerminalRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.Date");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Date:
		//    STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	
	public class SectionTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.resume.Resume.SectionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEXPERIENCEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEXPERIENCEExperienceKeyword_0_0 = (Keyword)cEXPERIENCEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPROJECTSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPROJECTSProjectsKeyword_1_0 = (Keyword)cPROJECTSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cEDUCATIONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cEDUCATIONEducationKeyword_2_0 = (Keyword)cEDUCATIONEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSKILLSEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSKILLSSkillsKeyword_3_0 = (Keyword)cSKILLSEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cINTERESTSEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cINTERESTSInterestsKeyword_4_0 = (Keyword)cINTERESTSEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cLANGUAGESEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cLANGUAGESLanguagesKeyword_5_0 = (Keyword)cLANGUAGESEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMETRICSEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMETRICSMetricsKeyword_6_0 = (Keyword)cMETRICSEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum SectionType:
		//    EXPERIENCE='Experience' |
		//    PROJECTS='Projects' |
		//    EDUCATION='Education' |
		//    SKILLS='Skills' |
		//    INTERESTS='Interests' |
		//    LANGUAGES='Languages' |
		//    METRICS='Metrics'
		//;
		public EnumRule getRule() { return rule; }
		
		//EXPERIENCE='Experience' |
		//PROJECTS='Projects' |
		//EDUCATION='Education' |
		//SKILLS='Skills' |
		//INTERESTS='Interests' |
		//LANGUAGES='Languages' |
		//METRICS='Metrics'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EXPERIENCE='Experience'
		public EnumLiteralDeclaration getEXPERIENCEEnumLiteralDeclaration_0() { return cEXPERIENCEEnumLiteralDeclaration_0; }
		
		//'Experience'
		public Keyword getEXPERIENCEExperienceKeyword_0_0() { return cEXPERIENCEExperienceKeyword_0_0; }
		
		//PROJECTS='Projects'
		public EnumLiteralDeclaration getPROJECTSEnumLiteralDeclaration_1() { return cPROJECTSEnumLiteralDeclaration_1; }
		
		//'Projects'
		public Keyword getPROJECTSProjectsKeyword_1_0() { return cPROJECTSProjectsKeyword_1_0; }
		
		//EDUCATION='Education'
		public EnumLiteralDeclaration getEDUCATIONEnumLiteralDeclaration_2() { return cEDUCATIONEnumLiteralDeclaration_2; }
		
		//'Education'
		public Keyword getEDUCATIONEducationKeyword_2_0() { return cEDUCATIONEducationKeyword_2_0; }
		
		//SKILLS='Skills'
		public EnumLiteralDeclaration getSKILLSEnumLiteralDeclaration_3() { return cSKILLSEnumLiteralDeclaration_3; }
		
		//'Skills'
		public Keyword getSKILLSSkillsKeyword_3_0() { return cSKILLSSkillsKeyword_3_0; }
		
		//INTERESTS='Interests'
		public EnumLiteralDeclaration getINTERESTSEnumLiteralDeclaration_4() { return cINTERESTSEnumLiteralDeclaration_4; }
		
		//'Interests'
		public Keyword getINTERESTSInterestsKeyword_4_0() { return cINTERESTSInterestsKeyword_4_0; }
		
		//LANGUAGES='Languages'
		public EnumLiteralDeclaration getLANGUAGESEnumLiteralDeclaration_5() { return cLANGUAGESEnumLiteralDeclaration_5; }
		
		//'Languages'
		public Keyword getLANGUAGESLanguagesKeyword_5_0() { return cLANGUAGESLanguagesKeyword_5_0; }
		
		//METRICS='Metrics'
		public EnumLiteralDeclaration getMETRICSEnumLiteralDeclaration_6() { return cMETRICSEnumLiteralDeclaration_6; }
		
		//'Metrics'
		public Keyword getMETRICSMetricsKeyword_6_0() { return cMETRICSMetricsKeyword_6_0; }
	}
	
	private final ProfileElements pProfile;
	private final MetadataElements pMetadata;
	private final UserdataElements pUserdata;
	private final SectionElements pSection;
	private final ExperienceElements pExperience;
	private final JobElements pJob;
	private final ProjectsElements pProjects;
	private final ProjectElements pProject;
	private final EducationElements pEducation;
	private final DegreeElements pDegree;
	private final SkillsElements pSkills;
	private final SkillElements pSkill;
	private final InterestsElements pInterests;
	private final LanguagesElements pLanguages;
	private final MetricsElements pMetrics;
	private final MetricElements pMetric;
	private final ExpressionElements pExpression;
	private final SubtractionElements pSubtraction;
	private final NumberLiteralElements pNumberLiteral;
	private final CustomizationElements pCustomization;
	private final RuleElements pRule;
	private final SectionTypeElements eSectionType;
	private final FilterElements pFilter;
	private final GeneralFilterElements pGeneralFilter;
	private final TemporalFilterElements pTemporalFilter;
	private final AllFilterElements pAllFilter;
	private final StringListElements pStringList;
	private final DateElements pDate;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ResumeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProfile = new ProfileElements();
		this.pMetadata = new MetadataElements();
		this.pUserdata = new UserdataElements();
		this.pSection = new SectionElements();
		this.pExperience = new ExperienceElements();
		this.pJob = new JobElements();
		this.pProjects = new ProjectsElements();
		this.pProject = new ProjectElements();
		this.pEducation = new EducationElements();
		this.pDegree = new DegreeElements();
		this.pSkills = new SkillsElements();
		this.pSkill = new SkillElements();
		this.pInterests = new InterestsElements();
		this.pLanguages = new LanguagesElements();
		this.pMetrics = new MetricsElements();
		this.pMetric = new MetricElements();
		this.pExpression = new ExpressionElements();
		this.pSubtraction = new SubtractionElements();
		this.pNumberLiteral = new NumberLiteralElements();
		this.pCustomization = new CustomizationElements();
		this.pRule = new RuleElements();
		this.eSectionType = new SectionTypeElements();
		this.pFilter = new FilterElements();
		this.pGeneralFilter = new GeneralFilterElements();
		this.pTemporalFilter = new TemporalFilterElements();
		this.pAllFilter = new AllFilterElements();
		this.pStringList = new StringListElements();
		this.pDate = new DateElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.resume.Resume".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Profile:
	//    metadata=Metadata
	//    userdata=Userdata
	//    sections+=Section+
	//    customization=Customization
	//;
	public ProfileElements getProfileAccess() {
		return pProfile;
	}
	
	public ParserRule getProfileRule() {
		return getProfileAccess().getRule();
	}
	
	//Metadata:
	//    'Metadata' 'style:' style=STRING 'font:' font=STRING 'imgPath:' imgPath=STRING
	//;
	public MetadataElements getMetadataAccess() {
		return pMetadata;
	}
	
	public ParserRule getMetadataRule() {
		return getMetadataAccess().getRule();
	}
	
	//Userdata:
	//    'Userdata' 'name:' name=STRING 'email:' email=STRING 'telephoneNumber:' telephoneNumber=STRING 'direction:' direction=STRING 'city:' city=STRING 'country:' country=STRING
	//;
	public UserdataElements getUserdataAccess() {
		return pUserdata;
	}
	
	public ParserRule getUserdataRule() {
		return getUserdataAccess().getRule();
	}
	
	//Section:
	//    Experience | Projects | Education | Skills | Interests | Languages | Metrics
	//;
	public SectionElements getSectionAccess() {
		return pSection;
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}
	
	//Experience:
	//    'Experience' 'language:' language=STRING jobs+=Job+
	//;
	public ExperienceElements getExperienceAccess() {
		return pExperience;
	}
	
	public ParserRule getExperienceRule() {
		return getExperienceAccess().getRule();
	}
	
	//Job:
	//    'title:' title=STRING
	//    'description:' description=StringList
	//    'company:' company=STRING
	//    'startDate:' startDate=Date
	//    'endDate:' endDate=Date
	//    'tags:' tags=StringList
	//;
	public JobElements getJobAccess() {
		return pJob;
	}
	
	public ParserRule getJobRule() {
		return getJobAccess().getRule();
	}
	
	//Projects:
	//    'Projects' 'language:' language=STRING projects+=Project+
	//;
	public ProjectsElements getProjectsAccess() {
		return pProjects;
	}
	
	public ParserRule getProjectsRule() {
		return getProjectsAccess().getRule();
	}
	
	//Project:
	//    'title:' title=STRING
	//    'description:' description=StringList
	//    'technologies:' technologies=StringList
	//    'link:' link=STRING
	//    'tags:' tags=StringList
	//;
	public ProjectElements getProjectAccess() {
		return pProject;
	}
	
	public ParserRule getProjectRule() {
		return getProjectAccess().getRule();
	}
	
	//Education:
	//    'Education' 'language:' language=STRING degrees+=Degree*
	//;
	public EducationElements getEducationAccess() {
		return pEducation;
	}
	
	public ParserRule getEducationRule() {
		return getEducationAccess().getRule();
	}
	
	//Degree:
	//    'title:' title=STRING
	//    'institution:' institution=STRING
	//    'graduationDate:' graduationDate=Date
	//    'country:' country=STRING
	//    'tags:' tags=StringList
	//;
	public DegreeElements getDegreeAccess() {
		return pDegree;
	}
	
	public ParserRule getDegreeRule() {
		return getDegreeAccess().getRule();
	}
	
	//Skills:
	//    'Skills' 'language:' language=STRING skills+=Skill+
	//;
	public SkillsElements getSkillsAccess() {
		return pSkills;
	}
	
	public ParserRule getSkillsRule() {
		return getSkillsAccess().getRule();
	}
	
	//Skill:
	//    'title:' title=STRING 'tags:' tags=StringList
	//;
	public SkillElements getSkillAccess() {
		return pSkill;
	}
	
	public ParserRule getSkillRule() {
		return getSkillAccess().getRule();
	}
	
	//Interests:
	//    'Interests' 'language:' language=STRING 'tags:' tags=StringList
	//;
	public InterestsElements getInterestsAccess() {
		return pInterests;
	}
	
	public ParserRule getInterestsRule() {
		return getInterestsAccess().getRule();
	}
	
	//Languages:
	//    'Languages' 'language:' language=STRING 'tags:' tags=StringList
	//;
	public LanguagesElements getLanguagesAccess() {
		return pLanguages;
	}
	
	public ParserRule getLanguagesRule() {
		return getLanguagesAccess().getRule();
	}
	
	//Metrics:
	//    'Metrics' 'language:' language=STRING metrics+=Metric+
	//;
	public MetricsElements getMetricsAccess() {
		return pMetrics;
	}
	
	public ParserRule getMetricsRule() {
		return getMetricsAccess().getRule();
	}
	
	//Metric:
	//    'Metric' name=STRING '=' expression=Expression
	//;
	public MetricElements getMetricAccess() {
		return pMetric;
	}
	
	public ParserRule getMetricRule() {
		return getMetricAccess().getRule();
	}
	
	//Expression:
	//    Subtraction
	//;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Subtraction returns Expression:
	//    NumberLiteral (
	//        {Subtraction.left=current} '-' right=NumberLiteral
	//    )*
	//;
	public SubtractionElements getSubtractionAccess() {
		return pSubtraction;
	}
	
	public ParserRule getSubtractionRule() {
		return getSubtractionAccess().getRule();
	}
	
	//NumberLiteral returns Expression:
	//    {NumberLiteral} value=INT
	//;
	public NumberLiteralElements getNumberLiteralAccess() {
		return pNumberLiteral;
	}
	
	public ParserRule getNumberLiteralRule() {
		return getNumberLiteralAccess().getRule();
	}
	
	//Customization:
	//    'Customization' 'include' 'Profile' 'where' 'language' language=STRING rules+=Rule*
	//;
	public CustomizationElements getCustomizationAccess() {
		return pCustomization;
	}
	
	public ParserRule getCustomizationRule() {
		return getCustomizationAccess().getRule();
	}
	
	//Rule:
	//    'include' sectionType=SectionType 'where' filter=Filter
	//;
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}
	
	//enum SectionType:
	//    EXPERIENCE='Experience' |
	//    PROJECTS='Projects' |
	//    EDUCATION='Education' |
	//    SKILLS='Skills' |
	//    INTERESTS='Interests' |
	//    LANGUAGES='Languages' |
	//    METRICS='Metrics'
	//;
	public SectionTypeElements getSectionTypeAccess() {
		return eSectionType;
	}
	
	public EnumRule getSectionTypeRule() {
		return getSectionTypeAccess().getRule();
	}
	
	//Filter:
	//    GeneralFilter | TemporalFilter | AllFilter
	//;
	public FilterElements getFilterAccess() {
		return pFilter;
	}
	
	public ParserRule getFilterRule() {
		return getFilterAccess().getRule();
	}
	
	//GeneralFilter:
	//    'tags' 'include' tag=STRING
	//;
	public GeneralFilterElements getGeneralFilterAccess() {
		return pGeneralFilter;
	}
	
	public ParserRule getGeneralFilterRule() {
		return getGeneralFilterAccess().getRule();
	}
	
	//TemporalFilter:
	//    ('startDate' 'after' startDate=Date) | ('endDate' 'before' endDate=Date)
	//;
	public TemporalFilterElements getTemporalFilterAccess() {
		return pTemporalFilter;
	}
	
	public ParserRule getTemporalFilterRule() {
		return getTemporalFilterAccess().getRule();
	}
	
	//AllFilter:
	//    {AllFilter} 'all'
	//;
	public AllFilterElements getAllFilterAccess() {
		return pAllFilter;
	}
	
	public ParserRule getAllFilterRule() {
		return getAllFilterAccess().getRule();
	}
	
	//StringList:
	//    '[' values+=STRING (',' values+=STRING)* ']'
	//;
	public StringListElements getStringListAccess() {
		return pStringList;
	}
	
	public ParserRule getStringListRule() {
		return getStringListAccess().getRule();
	}
	
	//Date:
	//    STRING
	//;
	public DateElements getDateAccess() {
		return pDate;
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
