/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.generator;

import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.example.resume.resume.Customization;
import org.xtext.example.resume.resume.Degree;
import org.xtext.example.resume.resume.Education;
import org.xtext.example.resume.resume.Experience;
import org.xtext.example.resume.resume.Filter;
import org.xtext.example.resume.resume.GeneralFilter;
import org.xtext.example.resume.resume.Interests;
import org.xtext.example.resume.resume.Job;
import org.xtext.example.resume.resume.Languages;
import org.xtext.example.resume.resume.Profile;
import org.xtext.example.resume.resume.Project;
import org.xtext.example.resume.resume.Projects;
import org.xtext.example.resume.resume.Rule;
import org.xtext.example.resume.resume.Section;
import org.xtext.example.resume.resume.Skill;
import org.xtext.example.resume.resume.Skills;
import org.xtext.example.resume.resume.StringList;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class ResumeGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final Profile profile = ((Profile) _head);
    InputOutput.<String>println(">>> ¡INTENTANDO GENERAR EL CV! <<<");
    if ((profile != null)) {
      fsa.generateFile("generated_cv.py", this.compile(profile));
    }
  }

  public CharSequence compile(final Profile p) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# --- Importaciones de tus clases de Python ---");
    _builder.newLine();
    _builder.append("from Models import Profile, Metadata, UserData, Experience, Projects, Education, Skills, Interests, Languages, Customization");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# --- Inicialización ---");
    _builder.newLine();
    _builder.append("cv = Profile(\"");
    String _name = p.getUserdata().getName();
    _builder.append(_name);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# --- Metadata y Userdata ---");
    _builder.newLine();
    _builder.append("cv.with_metadata(\"");
    String _style = p.getMetadata().getStyle();
    _builder.append(_style);
    _builder.append("\", \"");
    String _font = p.getMetadata().getFont();
    _builder.append(_font);
    _builder.append("\", \"");
    String _imgPath = p.getMetadata().getImgPath();
    _builder.append(_imgPath);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("cv.with_userdata(");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"");
    String _name_1 = p.getUserdata().getName();
    _builder.append(_name_1, "    ");
    _builder.append("\", ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("\"");
    String _email = p.getUserdata().getEmail();
    _builder.append(_email, "    ");
    _builder.append("\", ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("\"");
    String _telephoneNumber = p.getUserdata().getTelephoneNumber();
    _builder.append(_telephoneNumber, "    ");
    _builder.append("\", ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("\"");
    String _direction = p.getUserdata().getDirection();
    _builder.append(_direction, "    ");
    _builder.append("\", ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("\"");
    String _country = p.getUserdata().getCountry();
    _builder.append(_country, "    ");
    _builder.append("\", ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("\"");
    String _city = p.getUserdata().getCity();
    _builder.append(_city, "    ");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append(")");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("# --- Secciones ---");
    _builder.newLine();
    {
      EList<Section> _sections = p.getSections();
      for(final Section section : _sections) {
        _builder.append("    ");
        CharSequence _compileSection = this.compileSection(section);
        _builder.append(_compileSection, "    ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("# --- Personalización (Filtros) ---");
    _builder.newLine();
    {
      Customization _customization = p.getCustomization();
      boolean _tripleNotEquals = (_customization != null);
      if (_tripleNotEquals) {
        _builder.append("    ");
        _builder.append("customizer = Customization(cv)");
        _builder.newLine();
        {
          EList<Rule> _rules = p.getCustomization().getRules();
          for(final Rule rule : _rules) {
            {
              Filter _filter = rule.getFilter();
              if ((_filter instanceof GeneralFilter)) {
                _builder.append("customizer.add_filter(\"");
                String _literal = rule.getSectionType().getLiteral();
                _builder.append(_literal);
                _builder.append("\", \"TAGS\", \"");
                Filter _filter_1 = rule.getFilter();
                String _tag = ((GeneralFilter) _filter_1).getTag();
                _builder.append(_tag);
                _builder.append("\")");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        _builder.append("    ");
        _builder.append("# Aplicamos el filtro de lenguaje base para todas las secciones incluidas");
        _builder.newLine();
        {
          EList<Rule> _rules_1 = p.getCustomization().getRules();
          for(final Rule rule_1 : _rules_1) {
            _builder.append("    ");
            _builder.append("customizer.add_filter(\"");
            String _literal_1 = rule_1.getSectionType().getLiteral();
            _builder.append(_literal_1, "    ");
            _builder.append("\", \"LANGUAGE\", \"");
            String _language = p.getCustomization().getLanguage();
            _builder.append(_language, "    ");
            _builder.append("\")");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("# --- Construcción final ---");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("cv.build()");
    _builder.newLine();
    return _builder;
  }

  protected CharSequence _compileSection(final Experience e) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("exp = cv.add_experience(\"");
    String _language = e.getLanguage();
    _builder.append(_language);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    {
      EList<Job> _jobs = e.getJobs();
      for(final Job job : _jobs) {
        _builder.append("exp.add_job(\"");
        String _title = job.getTitle();
        _builder.append(_title);
        _builder.append("\", \"");
        String _company = job.getCompany();
        _builder.append(_company);
        _builder.append("\", \"");
        String _startDate = job.getStartDate();
        _builder.append(_startDate);
        _builder.append("\", \"");
        String _endDate = job.getEndDate();
        _builder.append(_endDate);
        _builder.append("\", ");
        CharSequence _compileList = this.compileList(job.getDescription());
        _builder.append(_compileList);
        _builder.append(", ");
        CharSequence _compileList_1 = this.compileList(job.getTags());
        _builder.append(_compileList_1);
        _builder.append(")");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  protected CharSequence _compileSection(final Projects proj) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("projects = cv.add_projects(\"");
    String _language = proj.getLanguage();
    _builder.append(_language);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    {
      EList<Project> _projects = proj.getProjects();
      for(final Project p : _projects) {
        _builder.append("projects.add_project(\"");
        String _title = p.getTitle();
        _builder.append(_title);
        _builder.append("\", \"");
        String _link = p.getLink();
        _builder.append(_link);
        _builder.append("\", ");
        CharSequence _compileList = this.compileList(p.getDescription());
        _builder.append(_compileList);
        _builder.append(", ");
        CharSequence _compileList_1 = this.compileList(p.getTechnologies());
        _builder.append(_compileList_1);
        _builder.append(", ");
        CharSequence _compileList_2 = this.compileList(p.getTags());
        _builder.append(_compileList_2);
        _builder.append(")");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  protected CharSequence _compileSection(final Education ed) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("education = cv.add_education(\"");
    String _language = ed.getLanguage();
    _builder.append(_language);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    {
      EList<Degree> _degrees = ed.getDegrees();
      for(final Degree d : _degrees) {
        _builder.append("education.add_degree(\"");
        String _title = d.getTitle();
        _builder.append(_title);
        _builder.append("\", \"");
        String _institution = d.getInstitution();
        _builder.append(_institution);
        _builder.append("\", \"");
        String _graduationDate = d.getGraduationDate();
        _builder.append(_graduationDate);
        _builder.append("\", \"");
        String _country = d.getCountry();
        _builder.append(_country);
        _builder.append("\", ");
        CharSequence _compileList = this.compileList(d.getTags());
        _builder.append(_compileList);
        _builder.append(")");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  protected CharSequence _compileSection(final Skills sk) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("skills = cv.add_skills(\"");
    String _language = sk.getLanguage();
    _builder.append(_language);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    {
      EList<Skill> _skills = sk.getSkills();
      for(final Skill s : _skills) {
        _builder.append("skills.add_skill(\"");
        String _title = s.getTitle();
        _builder.append(_title);
        _builder.append("\", ");
        CharSequence _compileList = this.compileList(s.getTags());
        _builder.append(_compileList);
        _builder.append(")");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  protected CharSequence _compileSection(final Interests in) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("cv.add_interests(\"");
    String _language = in.getLanguage();
    _builder.append(_language);
    _builder.append("\").add_interests(");
    CharSequence _compileList = this.compileList(in.getTags());
    _builder.append(_compileList);
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileSection(final Languages lang) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("cv.add_languages(\"");
    String _language = lang.getLanguage();
    _builder.append(_language);
    _builder.append("\").add_languages(");
    CharSequence _compileList = this.compileList(lang.getTags());
    _builder.append(_compileList);
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  public CharSequence compileList(final StringList sl) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("[");
    {
      if ((sl != null)) {
        {
          EList<String> _values = sl.getValues();
          boolean _hasElements = false;
          for(final String v : _values) {
            if (!_hasElements) {
              _hasElements = true;
            } else {
              _builder.appendImmediate(", ", "");
            }
            _builder.append("\"");
            _builder.append(v);
            _builder.append("\"");
          }
        }
      }
    }
    _builder.append("]");
    return _builder;
  }

  @XbaseGenerated
  public CharSequence compileSection(final Section ed) {
    if (ed instanceof Education) {
      return _compileSection((Education)ed);
    } else if (ed instanceof Experience) {
      return _compileSection((Experience)ed);
    } else if (ed instanceof Interests) {
      return _compileSection((Interests)ed);
    } else if (ed instanceof Languages) {
      return _compileSection((Languages)ed);
    } else if (ed instanceof Projects) {
      return _compileSection((Projects)ed);
    } else if (ed instanceof Skills) {
      return _compileSection((Skills)ed);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(ed).toString());
    }
  }
}
