/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.resume.ide.contentassist.antlr.internal.InternalResumeParser;
import org.xtext.example.resume.services.ResumeGrammarAccess;

public class ResumeParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ResumeGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ResumeGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSectionAccess().getAlternatives(), "rule__Section__Alternatives");
			builder.put(grammarAccess.getFilterAccess().getAlternatives(), "rule__Filter__Alternatives");
			builder.put(grammarAccess.getTemporalFilterAccess().getAlternatives(), "rule__TemporalFilter__Alternatives");
			builder.put(grammarAccess.getSectionTypeAccess().getAlternatives(), "rule__SectionType__Alternatives");
			builder.put(grammarAccess.getProfileAccess().getGroup(), "rule__Profile__Group__0");
			builder.put(grammarAccess.getMetadataAccess().getGroup(), "rule__Metadata__Group__0");
			builder.put(grammarAccess.getUserdataAccess().getGroup(), "rule__Userdata__Group__0");
			builder.put(grammarAccess.getExperienceAccess().getGroup(), "rule__Experience__Group__0");
			builder.put(grammarAccess.getJobAccess().getGroup(), "rule__Job__Group__0");
			builder.put(grammarAccess.getProjectsAccess().getGroup(), "rule__Projects__Group__0");
			builder.put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
			builder.put(grammarAccess.getEducationAccess().getGroup(), "rule__Education__Group__0");
			builder.put(grammarAccess.getDegreeAccess().getGroup(), "rule__Degree__Group__0");
			builder.put(grammarAccess.getSkillsAccess().getGroup(), "rule__Skills__Group__0");
			builder.put(grammarAccess.getSkillAccess().getGroup(), "rule__Skill__Group__0");
			builder.put(grammarAccess.getInterestsAccess().getGroup(), "rule__Interests__Group__0");
			builder.put(grammarAccess.getLanguagesAccess().getGroup(), "rule__Languages__Group__0");
			builder.put(grammarAccess.getCustomizationAccess().getGroup(), "rule__Customization__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getGeneralFilterAccess().getGroup(), "rule__GeneralFilter__Group__0");
			builder.put(grammarAccess.getTemporalFilterAccess().getGroup_0(), "rule__TemporalFilter__Group_0__0");
			builder.put(grammarAccess.getTemporalFilterAccess().getGroup_1(), "rule__TemporalFilter__Group_1__0");
			builder.put(grammarAccess.getStringListAccess().getGroup(), "rule__StringList__Group__0");
			builder.put(grammarAccess.getStringListAccess().getGroup_2(), "rule__StringList__Group_2__0");
			builder.put(grammarAccess.getProfileAccess().getMetadataAssignment_0(), "rule__Profile__MetadataAssignment_0");
			builder.put(grammarAccess.getProfileAccess().getUserdataAssignment_1(), "rule__Profile__UserdataAssignment_1");
			builder.put(grammarAccess.getProfileAccess().getSectionsAssignment_2(), "rule__Profile__SectionsAssignment_2");
			builder.put(grammarAccess.getProfileAccess().getCustomizationAssignment_3(), "rule__Profile__CustomizationAssignment_3");
			builder.put(grammarAccess.getMetadataAccess().getStyleAssignment_2(), "rule__Metadata__StyleAssignment_2");
			builder.put(grammarAccess.getMetadataAccess().getFontAssignment_4(), "rule__Metadata__FontAssignment_4");
			builder.put(grammarAccess.getMetadataAccess().getImgPathAssignment_6(), "rule__Metadata__ImgPathAssignment_6");
			builder.put(grammarAccess.getUserdataAccess().getNameAssignment_2(), "rule__Userdata__NameAssignment_2");
			builder.put(grammarAccess.getUserdataAccess().getEmailAssignment_4(), "rule__Userdata__EmailAssignment_4");
			builder.put(grammarAccess.getUserdataAccess().getTelephoneNumberAssignment_6(), "rule__Userdata__TelephoneNumberAssignment_6");
			builder.put(grammarAccess.getUserdataAccess().getDirectionAssignment_8(), "rule__Userdata__DirectionAssignment_8");
			builder.put(grammarAccess.getUserdataAccess().getCityAssignment_10(), "rule__Userdata__CityAssignment_10");
			builder.put(grammarAccess.getUserdataAccess().getCountryAssignment_12(), "rule__Userdata__CountryAssignment_12");
			builder.put(grammarAccess.getExperienceAccess().getLanguageAssignment_2(), "rule__Experience__LanguageAssignment_2");
			builder.put(grammarAccess.getExperienceAccess().getJobsAssignment_3(), "rule__Experience__JobsAssignment_3");
			builder.put(grammarAccess.getJobAccess().getTitleAssignment_1(), "rule__Job__TitleAssignment_1");
			builder.put(grammarAccess.getJobAccess().getDescriptionAssignment_3(), "rule__Job__DescriptionAssignment_3");
			builder.put(grammarAccess.getJobAccess().getCompanyAssignment_5(), "rule__Job__CompanyAssignment_5");
			builder.put(grammarAccess.getJobAccess().getStartDateAssignment_7(), "rule__Job__StartDateAssignment_7");
			builder.put(grammarAccess.getJobAccess().getEndDateAssignment_9(), "rule__Job__EndDateAssignment_9");
			builder.put(grammarAccess.getJobAccess().getTagsAssignment_11(), "rule__Job__TagsAssignment_11");
			builder.put(grammarAccess.getProjectsAccess().getLanguageAssignment_2(), "rule__Projects__LanguageAssignment_2");
			builder.put(grammarAccess.getProjectsAccess().getProjectsAssignment_3(), "rule__Projects__ProjectsAssignment_3");
			builder.put(grammarAccess.getProjectAccess().getTitleAssignment_1(), "rule__Project__TitleAssignment_1");
			builder.put(grammarAccess.getProjectAccess().getDescriptionAssignment_3(), "rule__Project__DescriptionAssignment_3");
			builder.put(grammarAccess.getProjectAccess().getTechnologiesAssignment_5(), "rule__Project__TechnologiesAssignment_5");
			builder.put(grammarAccess.getProjectAccess().getLinkAssignment_7(), "rule__Project__LinkAssignment_7");
			builder.put(grammarAccess.getProjectAccess().getTagsAssignment_9(), "rule__Project__TagsAssignment_9");
			builder.put(grammarAccess.getEducationAccess().getLanguageAssignment_2(), "rule__Education__LanguageAssignment_2");
			builder.put(grammarAccess.getEducationAccess().getDegreesAssignment_3(), "rule__Education__DegreesAssignment_3");
			builder.put(grammarAccess.getDegreeAccess().getTitleAssignment_1(), "rule__Degree__TitleAssignment_1");
			builder.put(grammarAccess.getDegreeAccess().getInstitutionAssignment_3(), "rule__Degree__InstitutionAssignment_3");
			builder.put(grammarAccess.getDegreeAccess().getGraduationDateAssignment_5(), "rule__Degree__GraduationDateAssignment_5");
			builder.put(grammarAccess.getDegreeAccess().getCountryAssignment_7(), "rule__Degree__CountryAssignment_7");
			builder.put(grammarAccess.getDegreeAccess().getTagsAssignment_9(), "rule__Degree__TagsAssignment_9");
			builder.put(grammarAccess.getSkillsAccess().getLanguageAssignment_2(), "rule__Skills__LanguageAssignment_2");
			builder.put(grammarAccess.getSkillsAccess().getSkillsAssignment_3(), "rule__Skills__SkillsAssignment_3");
			builder.put(grammarAccess.getSkillAccess().getTitleAssignment_1(), "rule__Skill__TitleAssignment_1");
			builder.put(grammarAccess.getSkillAccess().getTagsAssignment_3(), "rule__Skill__TagsAssignment_3");
			builder.put(grammarAccess.getInterestsAccess().getLanguageAssignment_2(), "rule__Interests__LanguageAssignment_2");
			builder.put(grammarAccess.getInterestsAccess().getTagsAssignment_4(), "rule__Interests__TagsAssignment_4");
			builder.put(grammarAccess.getLanguagesAccess().getLanguageAssignment_2(), "rule__Languages__LanguageAssignment_2");
			builder.put(grammarAccess.getLanguagesAccess().getTagsAssignment_4(), "rule__Languages__TagsAssignment_4");
			builder.put(grammarAccess.getCustomizationAccess().getLanguageAssignment_5(), "rule__Customization__LanguageAssignment_5");
			builder.put(grammarAccess.getCustomizationAccess().getRulesAssignment_6(), "rule__Customization__RulesAssignment_6");
			builder.put(grammarAccess.getRuleAccess().getSectionTypeAssignment_1(), "rule__Rule__SectionTypeAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getFilterAssignment_3(), "rule__Rule__FilterAssignment_3");
			builder.put(grammarAccess.getGeneralFilterAccess().getTagAssignment_2(), "rule__GeneralFilter__TagAssignment_2");
			builder.put(grammarAccess.getTemporalFilterAccess().getStartDateAssignment_0_2(), "rule__TemporalFilter__StartDateAssignment_0_2");
			builder.put(grammarAccess.getTemporalFilterAccess().getEndDateAssignment_1_2(), "rule__TemporalFilter__EndDateAssignment_1_2");
			builder.put(grammarAccess.getStringListAccess().getValuesAssignment_1(), "rule__StringList__ValuesAssignment_1");
			builder.put(grammarAccess.getStringListAccess().getValuesAssignment_2_1(), "rule__StringList__ValuesAssignment_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ResumeGrammarAccess grammarAccess;

	@Override
	protected InternalResumeParser createParser() {
		InternalResumeParser result = new InternalResumeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ResumeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ResumeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
